/*
 * NewWaitingDialog.java
 *
 * Created on 2007年4月28日, 下午5:49
 */

package com.cs.canalyzer.gui;

import com.cs.canalyzer.gui.GUIConst;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.plaf.metal.MetalProgressBarUI;

/**
 *
 * @author  msu
 */
public class StartupScreen extends javax.swing.JFrame {
    
    /** Creates new form NewWaitingDialog */
    public StartupScreen() {
        setUndecorated( true );

        myInit();

    }
    
    private void myInit() {
        initComponents();
        
        String imgurl = null;
        if(PropertyUtil.isNeutralLogoType()){
            imgurl = "/com/cs/canalyzer/gui/img/start_0.jpg";
        }else if(PropertyUtil.isIRLogoType()){
            imgurl = "/com/cs/canalyzer/gui/img/start_ir.jpg";
        }else if(PropertyUtil.isSUTOLogoType()){
            imgurl = "/com/cs/canalyzer/gui/img/start-suto.jpg";
        }else{
            imgurl = "/com/cs/canalyzer/gui/img/start.jpg";
        }
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource(imgurl)));
//        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource(
//            PropertyUtil.isIRLogoType()?"/com/cs/canalyzer/gui/img/start_ir.jpg":"/com/cs/canalyzer/gui/img/start.jpg")));


        jProgressBarMain.setMaximum(MAX_PROGRESS_VALUE);
        jProgressBarMain.setMinimum(MIN_PROGRESS_VALUE);
        jProgressBarMain.setValue(MIN_PROGRESS_VALUE);
        jProgressBarMain.setUI( new MetalProgressBarUI() );
        
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( (dim.width - WIDTH) / 2, (dim.height - HEIGHT) / 3, WIDTH, HEIGHT);
        
        //initTimer();
        resetStep();
    }

    private void initTimer() {
        /*timer = new Timer( ONE_STEP_TIME, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                oneStepForward();
            }
        });*/
        jProgressBarMain.setValue(MIN_PROGRESS_VALUE);
        step = STEP_SCALE;

        timer = new Timer();
        timer.scheduleAtFixedRate( new TimerTask() {
            public void run() { oneStepForward(); }
        }, 0 , ONE_STEP_TIME );
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jProgressBarMain = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelhowregmsg = new javax.swing.JLabel();
        jLabelhowregmsg1 = new javax.swing.JLabel();
        jLabelhowreglastmsg = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Please_Wait")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabelTitle.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource(
            PropertyUtil.isIRLogoType()?"/com/cs/canalyzer/gui/img/start_ir.jpg":"/com/cs/canalyzer/gui/img/start.jpg")));
getContentPane().add(jLabelTitle, java.awt.BorderLayout.CENTER);

jPanel1.setPreferredSize(new java.awt.Dimension(100, 105));
jPanel1.setLayout(new java.awt.BorderLayout());

jProgressBarMain.setForeground(new java.awt.Color(51, 196, 148));
jProgressBarMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
jProgressBarMain.setPreferredSize(new java.awt.Dimension(146, 20));
jPanel1.add(jProgressBarMain, java.awt.BorderLayout.CENTER);

jPanel2.setPreferredSize(new java.awt.Dimension(20, 100));

org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
jPanel2.setLayout(jPanel2Layout);
jPanel2Layout.setHorizontalGroup(
    jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
    .add(0, 20, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(0, 20, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

    jPanel3.setPreferredSize(new java.awt.Dimension(20, 100));

    org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(0, 20, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(0, 20, Short.MAX_VALUE)
    );

    jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

    jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
    jPanel4.setLayout(new java.awt.GridLayout(3, 0));

    jLabelhowregmsg.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
    jLabelhowregmsg.setForeground(new java.awt.Color(0, 153, 0));
    jLabelhowregmsg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelhowregmsg.setPreferredSize(new java.awt.Dimension(42, 35));
    jPanel4.add(jLabelhowregmsg);

    jLabelhowregmsg1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
    jLabelhowregmsg1.setForeground(new java.awt.Color(0, 153, 0));
    jLabelhowregmsg1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelhowregmsg1.setPreferredSize(new java.awt.Dimension(42, 35));
    jPanel4.add(jLabelhowregmsg1);

    jLabelhowreglastmsg.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
    jLabelhowreglastmsg.setForeground(new java.awt.Color(0, 153, 0));
    jLabelhowreglastmsg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelhowreglastmsg.setPreferredSize(new java.awt.Dimension(42, 35));
    jPanel4.add(jLabelhowreglastmsg);

    jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

    jLabelMessage.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
    jLabelMessage.setForeground(new java.awt.Color(102, 102, 102));
    jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelMessage.setText(bundle.getString("Please_wait")); // NOI18N
    jLabelMessage.setPreferredSize(new java.awt.Dimension(42, 35));
    jPanel1.add(jLabelMessage, java.awt.BorderLayout.NORTH);

    getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewWaitingDialog().setVisible(true);
            }
        });
    }*/
    
    /* delay is in millisecond
     */
    public void showUp( String message, TimerTask task, int delay ) {
        useProgressValue = false;
        
        setMessage( message );
        setVisible(true);
        
        ( new Timer() ).schedule( task, delay );
        
        //if( timer.isRunning() ) timer.restart();
        //else timer.start();
        initTimer();
    }
    
    /* default start delay is 10ms
     */ 
    public void showUp( String message, TimerTask task ) {
        showUp( message, task, DEFAULT_START_DELAY );
    }
    
    public void showUp( String message ) {
        useProgressValue = false;
        setMessage( message );
        setVisible(true);
        
        initTimer();
    }
    //add by be on 20090210.
     public void showUp( String leftdaymsg,String leftdaymsg1,String regmsgLast ) {
        useProgressValue = false;      
        setMessageReg( leftdaymsg );
        setMessageReg1( leftdaymsg1 );
        setMessageLastReg(regmsgLast);
        setVisible(true);
        
        initTimer();
    }

     //new concept ----------- begin
//    private String GRAPHIC_REFRESH_TEXT = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("trial_period_expires_in_days");
    private final int GRAPHIC_REFRESH_TEXT_SIZE = 23;
    private final String FONT_NAME = "SansSerif";
    public void showProgress(boolean value,int leftdays) {
        Graphics2D g2 = (Graphics2D) getGraphics();
//        if (value) {
             g2.setColor( new Color(255,0,51) );
//        }else{
//            Color bgcolor = new Color(238,238,238);
//            g2.setColor( bgcolor );
//        }
        String GRAPHIC_REFRESH_TEXT = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("trial_period_expires_in_days") + " " + leftdays +" "+java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("days")+".";
        g2.setFont( new Font( FONT_NAME, 1, GRAPHIC_REFRESH_TEXT_SIZE ));
        g2.drawString(GRAPHIC_REFRESH_TEXT,textW, textH);


    }
     // ------------------ end

    public void setMessageReg( String message ) {
         jLabelhowregmsg.setText( message );
    }
    public void setMessageReg1( String message ) {
         jLabelhowregmsg1.setText( message );
    }
    public void setMessageLastReg( String message ) {
         jLabelhowreglastmsg.setText( message );
    }


    /** similar like showUp, except it let upper caller to set progress by calling setProgressValue() 
     */
    public void showUpUsingProgressValue( String message, TimerTask task, int delay ) {
        resetStep();
        useProgressValue = true;

        setMessage( message );
        setVisible(true);
        
        ( new Timer() ).schedule( task, delay );
        
        //if( timer.isRunning() ) timer.restart();
        //else timer.start();
        initTimer();
   }
    
    /** similar like showUp, except it let upper caller to set progress by calling setProgressValue().
     * default delay is 10ms
     */
    public void showUpUsingProgressValue( String message, TimerTask task ) {
        showUpUsingProgressValue( message, task, DEFAULT_START_DELAY );
    }    
    public void unShow() {
        //if( timer.isRunning() ) timer.stop();
        if ( timer != null ) timer.cancel();
        //timer = null;
        
        dispose();
        //setVisible(false);
        //resetStep();
    }
  
    
    public void oneStepForward() {
        int value = jProgressBarMain.getValue();
        if ( useProgressValue ) 
            value = progressValue;
        else
            value += step;

        if ( value >= MAX_PROGRESS_VALUE ) step = -1 * STEP_SCALE;
        if ( value <= MIN_PROGRESS_VALUE ) step = STEP_SCALE;

        jProgressBarMain.setValue(value);
    }

    public void resetStep() {
        jProgressBarMain.setValue( MIN_PROGRESS_VALUE );
        progressValue = MIN_PROGRESS_VALUE;
        useProgressValue = false;
    }
    
    public void setMessage( String message ) {
        jLabelMessage.setText( message );
    }
    
    /** value is a percentage ranges from 0 ~ 100
     */ 
    public void setProgressValue( int value ) {
        if ( value >= 0 && value <= 100 ) {
            progressValue = ( MAX_PROGRESS_VALUE - MIN_PROGRESS_VALUE ) * value / 100;
        }
    }
    
    private final int WIDTH = 550;
    private final int HEIGHT = 530;
    private final int textW = WIDTH/2 - 150 ;
    private final int textH = HEIGHT/2 + 20;
    private final int MAX_PROGRESS_VALUE = 100;
    private final int MIN_PROGRESS_VALUE = 0;
    private final int STEP_SCALE = 2;
    private final int ONE_STEP_TIME = 300;  // in millisecond
    private final int DEFAULT_START_DELAY = 50; // in millisecond
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelhowreglastmsg;
    private javax.swing.JLabel jLabelhowregmsg;
    private javax.swing.JLabel jLabelhowregmsg1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBarMain;
    // End of variables declaration//GEN-END:variables
    
    private Timer timer;
    
    private boolean useProgressValue;
    private int progressValue;
    private int step;
}
