/*
 * About.java
 *
 * Created on 2005年4月6日, 下午5:52
 */

package com.cs.canalyzer.gui.dialog;

import com.cs.canalyzer.gui.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/** 
 *
 * @author  msu
 */
public class About extends javax.swing.JFrame {
    
    /** Creates new form About */
    public About() {
        initComponents();
        
        String imgurl=  null;
        if(PropertyUtil.isNeutralLogoType()){
            imgurl = "/com/cs/canalyzer/gui/img/about_0.jpg";
        }else if(PropertyUtil.isIRLogoType()){
            imgurl = "/com/cs/canalyzer/gui/img/about_ir.jpg";
        }else if(PropertyUtil.isSUTOLogoType()){
            imgurl = "/com/cs/canalyzer/gui/img/about_st.jpg";
        }else{
            imgurl = "/com/cs/canalyzer/gui/img/about.jpg";
        }        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(imgurl)));
//        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
//            PropertyUtil.isIRLogoType()?"/com/cs/canalyzer/gui/img/about_ir.jpg":"/com/cs/canalyzer/gui/img/about.jpg")));
        getGlassPane().addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dispose();
            }
        });
        getGlassPane().setVisible( true );        
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage());         
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( (dim.width - WIDTH ) / 2, (dim.height - HEIGHT) / 3, WIDTH, HEIGHT );        
        setUndecorated( true );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("About")); // NOI18N
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
            PropertyUtil.isIRLogoType()?"/com/cs/canalyzer/gui/img/about_ir.jpg":"/com/cs/canalyzer/gui/img/about.jpg")));
jPanel3.add(jLabel1);

getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);
}// </editor-fold>//GEN-END:initComponents
    
    
    private final int WIDTH = 720;
    private final int HEIGHT = 490;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
}
