/*
 * CommentPageDialog.java
 *
 * Created on 2008年3月17日, 下午5:28
 */

package com.cs.canalyzer.gui.dialog;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.Texts;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author  wolf
 */
public class CommentPageDialog extends javax.swing.JFrame {
    
    /** Creates new form CommentPageDialog */
    public CommentPageDialog( Texts texts ) {
        this.myTexts = texts;
        
        myInit();
    }
    
    private void myInit() {
        initComponents();
        // add on 20100511, KR's requirement.
        jLabel4.setText("("+java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Max_Rows")+" 11 )");

        jTextTitle.setText( myTexts.CommendPageTitle );
        jTextAreaContent.setText( myTexts.CommendPageBodyText );
         //add by be,on 20090305.
        //control the content which show on the cover page don't show scroll bar.
        controlTitleAndContent();
        
        setIconImage( new ImageIcon( getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );         
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( (dim.width - WIDTH) / 2, (dim.height - HEIGHT) / 4, WIDTH, HEIGHT );
        
        //temp
        jButtonClear.setVisible( false );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextAreaContent = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextTitle = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Comment_Page"));
        setResizable(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 35));
        jLabel1.setFont(DIALOG_FONT);
        jLabel1.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Content:"));
        jPanel3.add(jLabel1);

        jLabel4.setFont(DIALOG_FONT);
        jLabel4.setText("(MaxRows : 11 )");
        jPanel3.add(jLabel4);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jTextAreaContent.setColumns(20);
        jTextAreaContent.setFont(DIALOG_FONT);
        jTextAreaContent.setLineWrap(true);
        jTextAreaContent.setRows(10);
        jPanel1.add(jTextAreaContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 80));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Write_Report_Comment_Page"));
        jLabel2.setPreferredSize(new java.awt.Dimension(42, 40));
        jPanel2.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        jLabel3.setFont(DIALOG_FONT);
        jLabel3.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Title:"));
        jPanel4.add(jLabel3);

        jTextTitle.setFont(DIALOG_FONT);
        jTextTitle.setPreferredSize(new java.awt.Dimension(400, 21));
        jPanel4.add(jTextTitle);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 50));
        jButtonOK.setFont(DIALOG_FONT);
        jButtonOK.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("OK"));
        jButtonOK.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(DIALOG_FONT);
        jButtonCancel.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Cancel"));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonClear.setFont(DIALOG_FONT);
        jButtonClear.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Clear_Comment"));
        jButtonClear.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .add(jButtonClear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(19, 19, 19)
                .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonClear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        getContentPane().add(jPanel5, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        myTexts.CommendPageTitle = "";
        myTexts.CommendPageBodyText = "";
        dispose();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        //add by be, on 20090305.
        if(jTextTitle.getText().length() > 51){
           JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("The_title's_length_must_be_less_than_50."));
           return ;          
        } 
   
        try{    
            String str = jTextAreaContent.getText().trim();
            Rectangle rec = jTextAreaContent.modelToView(str.length());
           // System.out.println("========================"+rec.y / rec.height);
            if((rec.y / rec.height +1) > 11){
                 JOptionPane.showMessageDialog(null,java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("The_content's_max_rows_is_11."));
                 return ; 
            }
        }catch(BadLocationException  e){
            e.printStackTrace();
        }              
        
        myTexts.CommendPageTitle = jTextTitle.getText();
        myTexts.CommendPageBodyText = jTextAreaContent.getText();
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
private void controlTitleAndContent(){
    //control title
    jTextTitle.addKeyListener(new KeyListener(){          
        public void keyTyped(KeyEvent e){   
            if(jTextTitle.getText().length() > 50){
                   //JOptionPane.showMessageDialog(null,"the text content length more than 150");                 
                 e.setKeyChar('\0'); 
            }               
        } 
        public void keyPressed(KeyEvent e){
            if(jTextTitle.getText().length() > 50){
               //JOptionPane.showMessageDialog(null,"the text content length more than 150");                 
               e.setKeyChar('\0'); 
            }   
        }
        public void keyReleased(KeyEvent e){ }
   });
     
   //control content
   jTextAreaContent.addKeyListener(new KeyListener(){         
       public void keyTyped(KeyEvent e){ 
          
            try{    
                //System.out.println("jTextAreaContent.getText()="+jTextAreaContent.getText());
                String str = jTextAreaContent.getText().trim();
               
                Rectangle rec = jTextAreaContent.modelToView(str.length());
               // System.out.println("========================"+rec.y / rec.height);
                if((rec.y / rec.height +1) > 11){
                      e.setKeyChar('\0'); 
                }
            }catch(BadLocationException  ew){
                ew.printStackTrace();
            } 
           
//            if(jTextAreaContent.getRows() > 12){
//               //JOptionPane.showMessageDialog(null,"the text content length more than 150");                 
//               e.setKeyChar('\0'); 
//           }   
//           if(jTextAreaContent.getLineCount() > 12){
//               //JOptionPane.showMessageDialog(null,"the text content length more than 150");                 
//               e.setKeyChar('\0'); 
//           }   
//           if(jTextAreaContent.getText().length() > 585){
//               //JOptionPane.showMessageDialog(null,"the text content length more than 150");                 
//               e.setKeyChar('\0'); 
//           }     
       }   
       public void keyPressed(KeyEvent e){ }   
       public void keyReleased(KeyEvent e){ }   
  });   
    
}
    
    
    private final int WIDTH = 500;
    private final int HEIGHT = 600;
    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextArea jTextAreaContent;
    private javax.swing.JTextField jTextTitle;
    // End of variables declaration//GEN-END:variables
 
    private Texts myTexts;
    
}
