/*
 * SaveReportDialog.java
 *
 * Created on 2008年2月4日, 下午4:24
 */

package com.cs.canalyzer.gui.dialog;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.ReportFile;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author  wolf
 */
public class SaveReportDialog extends javax.swing.JFrame {
    
    /** Creates new form SaveReportDialog */
    public SaveReportDialog( ReportFile reportFile ) {
        this.myReportFile = reportFile;
        
        myInit();
    }
    
    private void myInit() {
        initComponents();
        
        buttonGroupType.add( jRadioTypeNoData );
        buttonGroupType.add( jRadioTypeWithData );
        
        setIconImage( new ImageIcon( getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );         
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( (dim.width - WIDTH) / 2, (dim.height - HEIGHT) / 4, WIDTH, HEIGHT );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupType = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioTypeNoData = new javax.swing.JRadioButton();
        jRadioTypeWithData = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Save_Report")); // NOI18N

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("Select_Contents_To_Save_")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(168, 40));
        getContentPane().add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jRadioTypeNoData.setFont(DIALOG_FONT);
        jRadioTypeNoData.setSelected(true);
        jRadioTypeNoData.setText(bundle.getString("Record_file_information_(_no_data_),_view_settings,_report")); // NOI18N
        jRadioTypeNoData.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioTypeNoData.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioTypeNoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTypeNoDataActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioTypeNoData);

        jRadioTypeWithData.setFont(DIALOG_FONT);
        jRadioTypeWithData.setText(bundle.getString("Record_file_with_data,_view_settings,_report")); // NOI18N
        jRadioTypeWithData.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioTypeWithData.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioTypeWithData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTypeWithDataActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioTypeWithData);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(10, 50));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 10));

        jButtonOK.setFont(DIALOG_FONT);
        jButtonOK.setText(bundle.getString("Save")); // NOI18N
        jButtonOK.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOK);

        jButtonCancel.setFont(DIALOG_FONT);
        jButtonCancel.setText(bundle.getString("Cancel")); // NOI18N
        jButtonCancel.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(20, 10));
        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioTypeWithDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTypeWithDataActionPerformed
        reportTypeSelected();
    }//GEN-LAST:event_jRadioTypeWithDataActionPerformed

    private void jRadioTypeNoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTypeNoDataActionPerformed
        reportTypeSelected();
    }//GEN-LAST:event_jRadioTypeNoDataActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter( ReportFile.REPORT_FILE_SUFFIX, 
                    ReportFile.REPORT_FILE_SUFFIX_FILTER, ReportFile.REPORT_FILE_SUFFIX_CAPTICAL_FILTER );
        GUIConst.FILE_CHOOSER.setFileFilter( filter );
//        if ( GUIConst.LOAD_FILE_PATH != null && !GUIConst.LOAD_FILE_PATH.isEmpty() )
//            GUIConst.FILE_CHOOSER.setSelectedFile( new File( GUIConst.LOAD_FILE_PATH ));
        boolean confirmed = false;
        String fileName = "";
        
        while ( !confirmed ) {
            if ( GUIConst.FILE_CHOOSER.showDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Save_Report") ) == JFileChooser.APPROVE_OPTION ) {
                fileName = GUIConst.FILE_CHOOSER.getSelectedFile().getAbsolutePath();
                GUIConst.LOAD_FILE_PATH = fileName;
                if ( GUIConst.FILE_CHOOSER.getSelectedFile().exists() ) {
                    switch ( JOptionPane.showConfirmDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("File_exists._Overwrite?"), java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Please_Confirm"), 
                                            JOptionPane.YES_NO_CANCEL_OPTION )) {
                        case JOptionPane.YES_OPTION: confirmed = true; break;
                        case JOptionPane.NO_OPTION: break;
                        case JOptionPane.CANCEL_OPTION: { dispose(); return; }
                        default: { dispose(); return; }
                    } 
                } else
                    confirmed = true;
            } else {
                dispose();
                return;
            }
        } // end while loop
        dispose();
        final String choseFileName = fileName;
        final NewWaitingDialog waitDlg = new NewWaitingDialog();
        waitDlg.showUp( java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Processing,_please_wait_..."),
                new TimerTask() {
            public void run() {
        
        if(myReportFile.saveReport( choseFileName, myReportType )){
//            dispose();
            if(waitDlg != null){
                waitDlg.unShow();
            }
            JOptionPane.showMessageDialog( null, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("report_saved_suc"));
        }else{
            if(waitDlg != null){
                waitDlg.unShow();
            }
//            dispose();
            JOptionPane.showMessageDialog( null, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("report_saved_fail"));
        }
          }
        });
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void reportTypeSelected() {
        if ( jRadioTypeNoData.isSelected() )
            myReportType = ReportFile.SAVE_REPORT_WITHOUT_DATA;
        else if ( jRadioTypeWithData.isSelected() )
            myReportType = ReportFile.SAVE_REPORT_WITH_DATA;
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
   
    private final int WIDTH = 500;
    private final int HEIGHT = 230;
    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupType;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioTypeNoData;
    private javax.swing.JRadioButton jRadioTypeWithData;
    // End of variables declaration//GEN-END:variables
    
    private int myReportType = ReportFile.SAVE_REPORT_WITHOUT_DATA;
    private ReportFile myReportFile;
    
}
