/*
 * DatabaseDialog.java
 *
 * Created on 2007年4月18日, 下午3:19
 */

package com.cs.canalyzer.gui.dialog;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.gui.PropertyUtil;
import com.cs.canalyzer.structs.CommonValue;
import com.cs.canalyzer.structs.DatabaseInformation;
import com.cs.database.CSMDF;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  msu
 */
public class SelectDatabaseDialog extends javax.swing.JFrame {
    
    /** Creates new form DatabaseDialog */
    public SelectDatabaseDialog( CommonValue common ) {
        this.theCommonValue = common;
        this.myDatabaseInformations = common.getDatabaseInformations();
        
        myInit();
    }
    
    private void myInit() {
        initComponents();
        
        addDatabaseInformation();
        jTableMain.setSelectionMode( ListSelectionModel.SINGLE_SELECTION );
        jTableMain.changeSelection( theCommonValue.getSelectedDatabaseIndex(), 0, false, false );
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x, y;
        x = ( dim.width - DIALOG_WIDTH ) / 2;
        y = ( dim.height - DIALOG_HEIGHT ) / 3;
        jDialogNew.setIconImage( new ImageIcon( getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );
        jDialogNew.setBounds( x, y, DIALOG_WIDTH, DIALOG_HEIGHT );
        
        x = ( dim.width - WIDTH ) / 2;
        y = ( dim.height - HEIGHT ) / 2;
        setIconImage( new ImageIcon( getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );
        setBounds( x, y, WIDTH, HEIGHT );
    }
    
    private void addDatabaseInformation() {
        mainModel = (DefaultTableModel) jTableMain.getModel();
        String[] row = new String[3];
       
        for ( ; mainModel.getRowCount() > 0; ) 
            mainModel.removeRow( 0 );
        //mainModel = new DefaultTableModel();
        
        for( DatabaseInformation dbInfo : myDatabaseInformations ) {
            row[0] = dbInfo.Name;
            row[1] = dbInfo.Description;
            row[2] = dbInfo.DatabasePath;
            mainModel.addRow( row );
        }
        //jTableMain.setModel( mainModel );
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogNew = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextDBDescription = new javax.swing.JTextField();
        jLabelNewDBDialogTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextDBName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonSelectFile = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelDBPath = new javax.swing.JLabel();
        jLabelDBPath1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSelectDB = new javax.swing.JButton();
        jButtonNewDB = new javax.swing.JButton();
        jButtonEditDB = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMain = new javax.swing.JTable();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        jDialogNew.setTitle(bundle.getString("Select_Database")); // NOI18N
        jDialogNew.setModal(true);
        jDialogNew.setResizable(false);

        jLabel1.setFont(DIALOG_FONT);
        jLabel1.setText(bundle.getString("Name:")); // NOI18N

        jTextDBDescription.setFont(DIALOG_FONT);
        jTextDBDescription.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextDBDescription.setText(DatabaseInformation.DEFAULT_DESCRIPTION);

        jLabelNewDBDialogTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelNewDBDialogTitle.setText(ADD_DATABASE_DIALOG_TITLE);

        jLabel3.setFont(DIALOG_FONT);
        jLabel3.setText(bundle.getString("Description:")); // NOI18N

        jTextDBName.setFont(DIALOG_FONT);
        jTextDBName.setText(DatabaseInformation.DEFAULT_NAME);

        jLabel4.setFont(DIALOG_FONT);
        jLabel4.setText(bundle.getString("Database_File_Path:")); // NOI18N

        jButtonSelectFile.setFont(DIALOG_FONT);
        jButtonSelectFile.setText(bundle.getString("Select")); // NOI18N
        jButtonSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectFileActionPerformed(evt);
            }
        });

        jButtonOK.setFont(DIALOG_FONT);
        jButtonOK.setText(bundle.getString("OK")); // NOI18N
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(DIALOG_FONT);
        jButtonCancel.setText(bundle.getString("Cancel")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelDBPath.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelDBPath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDBPath.setText(bundle.getString("(_please_select_file_path_)")); // NOI18N

        jLabelDBPath1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabelDBPath1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDBPath1.setText(bundle.getString("(_please_select_file_path_)")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 408, Short.MAX_VALUE)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jLabelDBPath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLabelDBPath1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 77, Short.MAX_VALUE)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jLabelDBPath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLabelDBPath1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jDialogNewLayout = new org.jdesktop.layout.GroupLayout(jDialogNew.getContentPane());
        jDialogNew.getContentPane().setLayout(jDialogNewLayout);
        jDialogNewLayout.setHorizontalGroup(
            jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialogNewLayout.createSequentialGroup()
                .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jDialogNewLayout.createSequentialGroup()
                        .add(111, 111, 111)
                        .add(jLabelNewDBDialogTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jDialogNewLayout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jDialogNewLayout.createSequentialGroup()
                                .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jLabel3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 75, Short.MAX_VALUE)
                                .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextDBDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextDBName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jDialogNewLayout.createSequentialGroup()
                                .add(jLabel4)
                                .add(52, 52, 52)
                                .add(jButtonSelectFile)
                                .add(0, 0, Short.MAX_VALUE)))))
                .add(51, 51, 51))
            .add(jDialogNewLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jDialogNewLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButtonOK)
                .add(30, 30, 30)
                .add(jButtonCancel)
                .add(48, 48, 48))
        );

        jDialogNewLayout.linkSize(new java.awt.Component[] {jButtonCancel, jButtonOK}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jDialogNewLayout.setVerticalGroup(
            jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialogNewLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jLabelNewDBDialogTitle)
                .add(35, 35, 35)
                .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextDBName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextDBDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(21, 21, 21)
                .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSelectFile)
                    .add(jLabel4))
                .add(18, 18, 18)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDialogNewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOK)
                    .add(jButtonCancel))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("Select_Database")); // NOI18N

        jPanel2.setPreferredSize(new java.awt.Dimension(110, 100));

        jButtonSelectDB.setFont(DIALOG_FONT);
        jButtonSelectDB.setText(bundle.getString("Select")); // NOI18N
        jButtonSelectDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDBActionPerformed(evt);
            }
        });

        jButtonNewDB.setFont(DIALOG_FONT);
        jButtonNewDB.setText(bundle.getString("New")); // NOI18N
        jButtonNewDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewDBActionPerformed(evt);
            }
        });

        jButtonEditDB.setFont(DIALOG_FONT);
        jButtonEditDB.setText(bundle.getString("Edit")); // NOI18N
        jButtonEditDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditDBActionPerformed(evt);
            }
        });

        jButtonExit.setFont(DIALOG_FONT);
        jButtonExit.setText(bundle.getString("Exit")); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonRemove.setFont(DIALOG_FONT);
        jButtonRemove.setText(bundle.getString("Remove")); // NOI18N
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonExit)
                    .add(jButtonRemove)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jButtonEditDB)
                        .add(jButtonNewDB)
                        .add(jButtonSelectDB)))
                .add(18, 18, 18))
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {jButtonEditDB, jButtonExit, jButtonNewDB, jButtonRemove, jButtonSelectDB}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonSelectDB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonNewDB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonEditDB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonRemove)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonExit)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(bundle.getString("Select_Database")); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(42, 50));
        getContentPane().add(jLabel6, java.awt.BorderLayout.NORTH);

        jPanel3.setPreferredSize(new java.awt.Dimension(30, 100));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 452, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(DIALOG_FONT);
        jLabel7.setText(bundle.getString("<html>Please_select_database_for_analyzation._<br><br>You_can_also_add_new_database_connection_or_edit_existing_one._</html>")); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(42, 100));
        jPanel4.add(jLabel7, java.awt.BorderLayout.SOUTH);

        jTableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Database Name", "Description", "Data File Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableMain);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        int[] indexes = jTableMain.getSelectedRows();
        if ( indexes.length <= 0 ) return;
        selectedIndex = indexes[0];        

        int reply;
        String tail = "";
        if ( selectedIndex == theCommonValue.getSelectedDatabaseIndex() ) {
            // this one is currently open
            reply = JOptionPane.showConfirmDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Selected_database_is_currently_open._Are_you_sure_to_remove_it?"), 
                    java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Please_confirm"), JOptionPane.YES_NO_OPTION );
            if ( reply != JOptionPane.OK_OPTION ) 
                return;
            theCommonValue.getDataBase().shutDown();
            tail = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<br><br>Please_select_another_one_to_open.<br><br>");
        } else {
            if ( selectedIndex < theCommonValue.getSelectedDatabaseIndex() ) {
                theCommonValue.setSelectedDatabaseIndex( theCommonValue.getSelectedDatabaseIndex() - 1 );
            }
        }
        
        myDatabaseInformations.remove( selectedIndex );
        selectedIndex = -1;
        addDatabaseInformation();
        JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<html>Database_connection_removed._") + tail + "</html>" );
        
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectFileActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode( JFileChooser.FILES_AND_DIRECTORIES );
        File dbDir;
        String fileName;
        
        fc.setSelectedFile(new File(jLabelDBPath.getText()));
        if ( fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION ) {
            
            dbDir = fc.getSelectedFile();            
            fileName = dbDir.getAbsolutePath();
            
            // get rid of the extension
            //fileName = fileName.substring( 0, fileName.lastIndexOf( "." ) );
            //jLabelDBPath.setText( fileName );
            if ( !dbDir.exists() ) {
                JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Directory_doesn't_exist._Please_try_again.") );
                return;
            }
            if ( !dbDir.isDirectory() ) {
                JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Please_select_a_directory_instead_of_a_file.") );
                return;
            }
            jLabelDBPath.setText( fileName );
            jLabelDBPath.setVisible(false);
            
            displayFilePath(fileName);
           
        }
    }//GEN-LAST:event_jButtonSelectFileActionPerformed

    private void displayFilePath(String fileName){
        
        if(fileName == null){
            jLabelDBPath1.setText( "" );
            return;
        }
        int len = fileName.length();
        int splitLen = 130 ;          
        int strFileNameCount = len/splitLen;          
        int strFileNameOther = len%splitLen;
        if(strFileNameOther > 0){
            strFileNameCount += 1 ;
        }

        String strTmp  = "<html>";
        String displayFileNamePath = fileName;
        for(int i = 0; i < strFileNameCount ; i++){
            if(i == (strFileNameCount-1)){
                strTmp += fileName.substring(splitLen*i,len)+"</html>";
            }else{
                strTmp += fileName.substring(splitLen*i,splitLen*(i+1))+"<br>";
            }   
            displayFileNamePath = strTmp;
        }

        jLabelDBPath1.setText( displayFileNamePath );
    }
    
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonEditDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditDBActionPerformed
        int[] indexes = jTableMain.getSelectedRows();
        if ( indexes.length <= 0 ) return;
        selectedIndex = indexes[0];        
        
        DatabaseInformation dbInfo = myDatabaseInformations.get( indexes[0] );
        try {
            jLabelNewDBDialogTitle.setText( EDIT_DATABASE_DIALOG_TITLE );
            jTextDBName.setText( dbInfo.Name );
//            System.out.println("jTextDBName.getWidth()="+jTextDBName.getWidth()+"  jTextDBName.getHeight()="+jTextDBName.getHeight());

            jTextDBDescription.setText( dbInfo.Description );
//            System.out.println("jTextDBDescription.getWidth()="+jTextDBDescription.getWidth()+"  jTextDBDescription.getHeight()="+jTextDBDescription.getHeight());

            jLabelDBPath.setText( dbInfo.DatabasePath );
            jLabelDBPath.setVisible(false);
            
            displayFilePath( dbInfo.DatabasePath);
            
            jDialogNew.setModalityType( JDialog.ModalityType.APPLICATION_MODAL );
            jDialogNew.setVisible( true );
            
            //jTableMain.
        } catch ( Exception e ) {
            System.out.println( "jButtonEditDBActionPerformed: " + e.getMessage() );
        }
        
    }//GEN-LAST:event_jButtonEditDBActionPerformed

    private void jButtonNewDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewDBActionPerformed
        selectedIndex = -1;
        
        jLabelNewDBDialogTitle.setText( ADD_DATABASE_DIALOG_TITLE );
        jTextDBName.setText( DatabaseInformation.DEFAULT_NAME );
        jTextDBDescription.setText( DatabaseInformation.DEFAULT_DESCRIPTION );
        jLabelDBPath.setText( "" );
        jLabelDBPath.setVisible(false);
        jLabelDBPath1.setText( "" );
        jDialogNew.setModalityType( JDialog.ModalityType.APPLICATION_MODAL );
        jDialogNew.setVisible( true );

    }//GEN-LAST:event_jButtonNewDBActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        jDialogNew.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        DatabaseInformation dbInfo = new DatabaseInformation();
        dbInfo.Name = jTextDBName.getText();
        dbInfo.Description = jTextDBDescription.getText();
        dbInfo.DatabasePath = jLabelDBPath.getText();
        if ( selectedIndex >= 0 ) {
            if ( selectedIndex == theCommonValue.getSelectedDatabaseIndex() &&
                    myDatabaseInformations.get( selectedIndex ).DatabasePath.compareTo( dbInfo.DatabasePath ) != 0 ) {
                CSMDF db = theCommonValue.getDataBase();
                db.shutDown();
                if ( db.openDatabase( dbInfo.DatabasePath )) {
                    theCommonValue.setSelectedDatabaseIndex( selectedIndex );
                    theCommonValue.setDataBase( db );
                    JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Database_open_successfully.") );
                    //dispose();
                } else {
                    db.openDatabase( myDatabaseInformations.get( theCommonValue.getSelectedDatabaseIndex() ).DatabasePath );
                    JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<html>Open_database_failed._Please_check:<br><br>1)_is_the_database_path_setting_correct?") +
                            java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString(
                                    PropertyUtil.isIRLogoType()?"<br>2)_is_the_database_being_used_by_another_problem_(_IRSoft_)?<br><br>":"<br>2)_is_the_database_being_used_by_another_problem_(_CSSoft_)?<br><br>") );
                }
            }
            myDatabaseInformations.set( selectedIndex, dbInfo );
        } else
            myDatabaseInformations.add( dbInfo );
        
        jDialogNew.dispose();
        addDatabaseInformation();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonSelectDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDBActionPerformed
        int[] indexes = jTableMain.getSelectedRows();
        if ( indexes.length <= 0 ) return;
        selectedIndex = indexes[0];
        
//        if ( selectedIndex == theCommonValue.getSelectedDatabaseIndex() ) {
//            // same old one
//            JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Selected_database_has_already_been_opened.") );
//            return;
//        }
        
        DatabaseInformation dbInfo = myDatabaseInformations.get( selectedIndex );
        CSMDF db = theCommonValue.getDataBase();
        db.shutDown();
        if ( db.openDatabase( dbInfo.DatabasePath )) {
            theCommonValue.setSelectedDatabaseIndex( selectedIndex );
            theCommonValue.setDataBase( db );
            JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Database_open_successfully.") );
            dispose();
        } else {
            db.openDatabase( myDatabaseInformations.get( theCommonValue.getSelectedDatabaseIndex() ).DatabasePath );
            JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<html>Open_database_failed._Please_check:<br><br>1)_is_the_database_path_setting_correct?") +
                    java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString(PropertyUtil.isIRLogoType()?"<br>2)_is_the_database_being_used_by_another_problem_(_IRSoft_)?<br><br>":"<br>2)_is_the_database_being_used_by_another_problem_(_CSSoft_)?<br><br>") );
        }
        
    }//GEN-LAST:event_jButtonSelectDBActionPerformed
    
    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    private final int DIALOG_WIDTH = 440, DIALOG_HEIGHT = 400;
    private final int WIDTH = 600, HEIGHT = 600;

    private final String ADD_DATABASE_DIALOG_TITLE = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Add_Database_Connection");
    private final String EDIT_DATABASE_DIALOG_TITLE = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Edit_Database_Connection");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEditDB;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNewDB;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonSelectDB;
    private javax.swing.JButton jButtonSelectFile;
    private javax.swing.JDialog jDialogNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDBPath;
    private javax.swing.JLabel jLabelDBPath1;
    private javax.swing.JLabel jLabelNewDBDialogTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMain;
    private javax.swing.JTextField jTextDBDescription;
    private javax.swing.JTextField jTextDBName;
    // End of variables declaration//GEN-END:variables
    
    
    private int selectedIndex = -1;  // set it to negative when create new database
    
    private DefaultTableModel mainModel;
    
    private ArrayList<DatabaseInformation> myDatabaseInformations;
    private CommonValue theCommonValue;
    
}
