/*
 * TimeDialog.java
 *
 * Created on 2007年5月15日, 下午6:11
 */

package com.cs.canalyzer.gui.dialog;

import java.awt.Window;

/**
 *
 * @author  msu
 */
public class TimeDialog extends javax.swing.JFrame {
    
    /** Creates new form TimeDialog */
    public TimeDialog() {
        
    }
    
    private void myInit() {
        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setLayout(new java.awt.BorderLayout());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonOK.setFont(new java.awt.Font("Dialog", 0, 12));
        jButtonOK.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("OK"));
        jButtonOK.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel2.add(jButtonOK);

        jButtonCancel.setFont(new java.awt.Font("Dialog", 0, 12));
        jButtonCancel.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Cancel"));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel2.add(jButtonCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeDialog().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
}
