const express = require('express');
const router = express.Router();
const axios = require('axios');
const pool = require('../db');
const constants = require('../config/constants');
const crypto = require('../utils/crypto');
const helpers = require('../utils/helpers');

// --- S520 Routes ---
function getS520license(req, res, kw) {
    let sql = 'select s.id,s.sn,s.note,s.license,s.createdatetime from s520licenses s';
    sql += " ORDER BY s.createdatetime DESC limit 200";
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ err });
        connection.query(sql, (error, rows) => {
            if (error) res.status(202).json({ err: error });
            else res.status(200).json(rows);
            connection.release();
        });
    });
}

router.get(constants.API_URL + constants.API_URL_S520_LICENSES, (req, res) => {
    getS520license(req, res, req.query.kw);
});

router.post(constants.API_URL + constants.API_URL_S520_LICENSES, (req, res) => {
    const { sn, note, license } = req.body;
    // Prefer the license generated by the frontend (JS version of license_gen.py)
    const key = license || crypto.base64ToHex(crypto.encryption(sn, 'cQfTjWnZr4u7x!A%D*F-JaNdRgUkXp2s'));
    const sn_props = [[sn, note, key, new Date()]];
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ err });
        connection.query('insert into s520licenses(sn, note, license, createdatetime) values ?', [sn_props], (error, done) => {
            if (error) {
                res.status(200).json({ msg: error });
            } else {
                helpers.createEvent(connection, req.session.loginName, constants.EVENT_TYPE_CREATE, constants.PRODUCT_TYPE_S520, sn + " with note: " + note);
                res.json({ license: key });
            }
            connection.release();
        });
    });
});

// --- S332 Routes ---
function getS332license(req, res, kw) {
    let sql = 'select s.id,s.machine_code,s.note,s.license,s.createdatetime,s.create_by from s332licenses s';
    sql += " ORDER BY s.createdatetime DESC limit 200";
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ err });
        connection.query(sql, (error, rows) => {
            if (error) res.status(202).json({ err: error });
            else res.status(200).json(rows);
            connection.release();
        });
    });
}

router.get(constants.API_URL + constants.API_URL_S332_LICENSES, (req, res) => {
    getS332license(req, res, req.query.kw);
});

router.post(constants.API_URL + constants.API_URL_S332_LICENSES, (req, res) => {
    const { machine_code, note, license } = req.body;
    const create_by = req.session.loginName || 'unknown';
    const sn_props = [[machine_code, note, license, new Date(), create_by]];
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ err });
        connection.query('insert into s332licenses(machine_code, note, license, createdatetime, create_by) values ?', [sn_props], (error, done) => {
            if (error) {
                res.status(200).json({ msg: error });
            } else {
                helpers.createEvent(connection, req.session.loginName, constants.EVENT_TYPE_CREATE, constants.PRODUCT_TYPE_S332, machine_code + " with note: " + note);
                res.json({ license: license });
            }
            connection.release();
        });
    });
});

// --- S4A Routes ---
function getS4Alicense(req, res, kw) {
    let sql = 'select s.id,s.sn,s.note,s.state,s.hk, s.cn, s.eu, s.createdatetime from s4a_remote_serialnumber s';
    sql += " ORDER BY s.createdatetime DESC limit 200";
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ err });
        connection.query(sql, (error, rows) => {
            if (error) res.status(202).json({ err: error });
            else res.status(200).json(rows);
            connection.release();
        });
    });
}

router.get(constants.API_URL + constants.API_URL_S4A_LICENSES + 's', (req, res) => {
    getS4Alicense(req, res, req.query.kw);
});

router.put(constants.API_URL + constants.API_URL_S4A_LICENSES, (req, res) => {
    const { id, sn, currlocation, newlocation } = req.body;
    let cnValue = 0, hkValue = 0, euValue = 0;
    if (newlocation === "1") cnValue = 1;
    else if (newlocation === "2") hkValue = 1;
    else if (newlocation === "3") euValue = 1;
    else hkValue = 1;

    axios.post('http://sl-hk.suto-portal.com:8000/v1/delLocation', { token: "one_time_secret", deviceID: sn, locationID: currlocation })
        .then(response => {
            if (response.data.status === 'success') {
                axios.post('http://sl-hk.suto-portal.com:8000/v1/setLocation', { token: "one_time_secret", deviceID: sn, locationID: newlocation })
                    .then(response => {
                        if (response.data.status === 'success') {
                            pool.getConnection((err, connection) => {
                                connection.query('update s4a_remote_serialnumber set cn = ?, hk = ?, eu = ? where id = ?', [cnValue, hkValue, euValue, id], (error) => {
                                    if (error) res.status(202).json({ err: error });
                                    else res.status(200).json({ id });
                                    connection.release();
                                });
                            });
                        } else res.status(202).json({ msg: response.data.error });
                    })
                    .catch(err => res.status(202).json({ msg: err.response.data.error }));
            } else res.status(202).json({ msg: response.data.error });
        })
        .catch(err => res.status(202).json({ msg: err.response.data.error }));
});

// --- S4CUS Routes ---
router.get(constants.API_URL + constants.API_URL_S4CUS_LICENSES, (req, res) => {
    let sql = 'select s.sn,s.note,s.sntype,s.state,s.company,s.createdatetime from s4cus_serialnumber s';
    sql += " ORDER BY s.createdatetime DESC limit 200";
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ err });
        connection.query(sql, (error, rows) => {
            if (error) res.status(202).json({ err: error });
            else res.status(200).json(rows);
            connection.release();
        });
    });
});

router.post('/s4cusregistration', (req, res) => {
    const { deviceid, sn } = req.body;
    pool.getConnection((err, connection) => {
        if (err) return res.status(400).json({ err });
        connection.query('select * from s4cus_serialnumber where sn = ?', [sn], (error, lrows) => {
            if (error) {
                res.status(400).json({ err: error });
            } else if (lrows.length === 0) {
                res.status(202).json({ err: 'serial number not found' });
            } else {
                const row = lrows[0];
                if (row.state === 0) {
                    connection.query('update s4cus_serialnumber set state = 1, deviceid = ? where sn = ?', [deviceid, sn], (err) => {
                        if (err) res.status(202).json({ err: 'register fail' });
                        else res.status(200).send(crypto.encryptAES(JSON.stringify(row)));
                    });
                } else if (row.state === 1 && deviceid === row.deviceid) {
                    res.status(200).send(crypto.encryptAES(JSON.stringify(row)));
                } else {
                    res.status(202).json({ err: 'bound to other device or blocked' });
                }
            }
            connection.release();
        });
    });
});

// --- Calibration Routes ---
router.get(constants.API_URL + constants.API_URL_CALIBRATION_LICENSES + 's', (req, res) => {
    let kw = req.query.kw;
    let sql = 'select s.id,s.sn,s.company,s.note,s.state,s.createdatetime from calibrationlicenses s';
    if (kw) sql += ' where s.sn like ' + pool.escape('%' + kw + '%') + ' or s.company like ' + pool.escape('%' + kw + '%');
    sql += " ORDER BY s.createdatetime DESC limit 200";
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ err });
        connection.query(sql, (error, rows) => {
            if (error) res.status(202).json({ err: error });
            else res.status(200).json(rows);
            connection.release();
        });
    });
});

router.post("/calibrationSystem/LicenseStatus", (req, res) => {
    const { uuid, licenseKey } = req.body;
    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ errNo: 5, errMsg: err });
        connection.query("select * from calibrationlicenses where sn = ? ORDER BY createdatetime DESC limit 1", [licenseKey], (error, rows) => {
            if (error || rows.length === 0) {
                res.status(202).json({ errNo: 1, errMsg: "not existed" });
            } else {
                const obj = rows[0];
                if (obj.state === 0) {
                    connection.query("update calibrationlicenses set localid=?, state=1 where sn=?", [uuid, licenseKey], (err) => {
                        if (err) res.status(202).json({ errNo: 5, errMsg: "sql error" });
                        else res.status(202).json({ errNo: 0, errMsg: "license valid" });
                    });
                } else if (obj.state === 1 && obj.localid === uuid) {
                    res.status(202).json({ errNo: 0, errMsg: "license valid" });
                } else {
                    res.status(202).json({ errNo: 4, errMsg: "invalid state" });
                }
            }
            connection.release();
        });
    });
});

router.get(constants.API_URL + constants.API_URL_S4A_LICENSES, (req, res) => {
    const { sn } = req.query;
    axios.post('http://sl-hk.suto-portal.com:8000/v1/getLocation', { token: "one_time_secret", deviceID: sn })
        .then(response => res.status(200).json(response.data))
        .catch(err => {
            if (err.response && err.response.data.code === 5) res.status(202).json({ msg: 'Not found in server' });
            else res.status(202).json({ msg: err.response ? err.response.data.error : err.message });
        });
});

router.post(constants.API_URL + constants.API_URL_S4A_LICENSES, (req, res) => {
    const { sn, note, location } = req.body;
    let cnValue = 0, hkValue = 1, euValue = 0;
    if (location === "1") { cnValue = 1; hkValue = 0; }
    else if (location === "3") { euValue = 1; hkValue = 0; }

    pool.getConnection((err, connection) => {
        if (err) return res.status(202).json({ msg: err });
        connection.query('select * from s4a_remote_serialnumber where sn = ?', [sn], (error, rows) => {
            if (rows && rows.length > 0) {
                connection.release();
                return res.status(202).json({ msg: 'Already exists' });
            }
            axios.post('http://sl-hk.suto-portal.com:8000/v1/setLocation', { token: "one_time_secret", deviceID: sn, locationID: location })
                .then(response => {
                    if (response.data.status === 'success') {
                        const props = [[sn, note, cnValue, hkValue, euValue, new Date()]];
                        connection.query('insert into s4a_remote_serialnumber(sn,note,cn,hk,eu,createdatetime) values ?', [props], (err) => {
                            if (!err) helpers.createEvent(connection, req.session.loginName, constants.EVENT_TYPE_CREATE, constants.PRODUCT_TYPE_S4A, sn);
                            res.json({ license: sn });
                            connection.release();
                        });
                    } else {
                        res.status(202).json({ msg: response.data.error });
                        connection.release();
                    }
                })
                .catch(err => {
                    res.status(202).json({ msg: err.response ? err.response.data.error : err.message });
                    connection.release();
                });
        });
    });
});

router.post(constants.API_URL + constants.API_URL_S4A_LICENSES + constants.API_URL_DELETE_TAIL, (req, res) => {
    const { id, sn, location } = req.body;
    axios.post('http://sl-hk.suto-portal.com:8000/v1/delLocation', { token: "one_time_secret", deviceID: sn, locationID: location })
        .then(() => {
            pool.getConnection((err, connection) => {
                connection.query('delete from s4a_remote_serialnumber where id = ?', [id], () => {
                    helpers.createEvent(connection, req.session.loginName, constants.EVENT_TYPE_DELETE, constants.PRODUCT_TYPE_S4A, sn);
                    res.status(200).json({ sn });
                    connection.release();
                });
            });
        })
        .catch(err => res.status(202).json({ msg: err.response ? err.response.data.error : err.message }));
});

// --- S4CUS Routes Cont. ---
router.put(constants.API_URL + constants.API_URL_S4CUS_LICENSES, (req, res) => {
    const { sn, state } = req.body;
    pool.getConnection((err, connection) => {
        connection.query('update s4cus_serialnumber set state = ? where sn = ?', [state, sn], (error) => {
            if (error) res.status(202).json({ err: error });
            else res.status(200).json({ state });
            connection.release();
        });
    });
});

router.post(constants.API_URL + constants.API_URL_S4CUS_LICENSES, (req, res) => {
    const { note, company, sntype } = req.body;
    const sn = helpers.generateMixedWithoutCheckExist(16);
    const props = [[sn, sntype, company, note, new Date()]];
    pool.getConnection((err, connection) => {
        connection.query('insert into s4cus_serialnumber(sn, sntype, company, note, createdatetime) values ?', [props], (error) => {
            if (!error) helpers.createEvent(connection, req.session.loginName, constants.EVENT_TYPE_CREATE, constants.PRODUCT_TYPE_S4C_US, sn);
            res.json({ license: sn });
            connection.release();
        });
    });
});

// --- Calibration Routes Cont. ---
router.put(constants.API_URL + constants.API_URL_CALIBRATION_LICENSES, (req, res) => {
    const { sn, state } = req.body;
    if (!req.session.loginName) return res.status(202).json({ err: 'Need login.' });
    pool.getConnection((err, connection) => {
        connection.query('update calibrationlicenses set state = ? where sn = ?', [state, sn], (error) => {
            if (error) res.status(202).json({ err: error });
            else res.status(200).json({ sn, state });
            connection.release();
        });
    });
});

router.post(constants.API_URL + constants.API_URL_CALIBRATION_LICENSES, (req, res) => {
    const { company, note } = req.body;
    helpers.generateMixedInTable(16, 'calibrationlicenses', (licensestr) => {
        if (licensestr) {
            const props = [[licensestr, company, note, new Date()]];
            pool.getConnection((err, connection) => {
                connection.query('insert into calibrationlicenses(sn, company, note, createdatetime) values ?', [props], (error) => {
                    if (!error) helpers.createEvent(connection, req.session.loginName, constants.EVENT_TYPE_CREATE, constants.PRODUCT_TYPE_CALIBRATION, licensestr);
                    res.json({ license: licensestr });
                    connection.release();
                });
            });
        }
    });
});

module.exports = router;
