/*
 * ExportDialog.java
 *
 * Created on February 22, 2008, 5:18 PM
 */

package com.cs.canalyzer.export;

import com.cs.canalyzer.export.JTable2PdfExportAction;
import com.cs.canalyzer.gui.Base;
import java.awt.Container;
import java.awt.event.KeyEvent;

/**
 *
 * @author  ll
 */
public class ExportDialog extends javax.swing.JDialog {
   protected Base base;
   
   /** Creates new form ExportDialog */
   public ExportDialog(Base base, boolean modal) {
      super(base, modal);
      initComponents();
      
      this.base = base;
      setTitle(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Export_To_PDF"));
      getRootPane().setDefaultButton(exportButton);
      setLocationRelativeTo(base);
      
     
      pdfGraphRadioButton.setMnemonic(KeyEvent.VK_4);
      pdfStatRadioButton.setMnemonic(KeyEvent.VK_5);
      pdfFullRadioButton.setMnemonic(KeyEvent.VK_6);
      pdfDetailedRadioButton.setMnemonic(KeyEvent.VK_7);
    
      
      if (base.hasDailyData() == false) {
         pdfDetailedRadioButton.setVisible(false);
      } else {
         pdfFullRadioButton.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Standard_report"));
      }
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        pdfPanel = new javax.swing.JPanel();
        pdfGraphRadioButton = new javax.swing.JRadioButton();
        pdfStatRadioButton = new javax.swing.JRadioButton();
        pdfFullRadioButton = new javax.swing.JRadioButton();
        pdfDetailedRadioButton = new javax.swing.JRadioButton();
        exportPanel = new javax.swing.JPanel();
        exportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        pdfPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Export_to_a_PDF_File"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), java.awt.Color.blue)); // NOI18N

        buttonGroup.add(pdfGraphRadioButton);
        pdfGraphRadioButton.setSelected(true);
        pdfGraphRadioButton.setText(bundle.getString("This_graph")); // NOI18N
        pdfGraphRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pdfGraphRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup.add(pdfStatRadioButton);
        pdfStatRadioButton.setText(bundle.getString("Statistics_report")); // NOI18N
        pdfStatRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pdfStatRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup.add(pdfFullRadioButton);
        pdfFullRadioButton.setText(bundle.getString("Standard_report")); // NOI18N
        pdfFullRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pdfFullRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup.add(pdfDetailedRadioButton);
        pdfDetailedRadioButton.setText(bundle.getString("Detailed_full_report")); // NOI18N
        pdfDetailedRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pdfDetailedRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pdfDetailedRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pdfDetailedRadioButtonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pdfPanelLayout = new javax.swing.GroupLayout(pdfPanel);
        pdfPanel.setLayout(pdfPanelLayout);
        pdfPanelLayout.setHorizontalGroup(
            pdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pdfGraphRadioButton)
                    .addComponent(pdfStatRadioButton)
                    .addComponent(pdfFullRadioButton)
                    .addComponent(pdfDetailedRadioButton))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        pdfPanelLayout.setVerticalGroup(
            pdfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pdfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pdfGraphRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdfStatRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdfFullRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdfDetailedRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        exportButton.setText(bundle.getString("Export")); // NOI18N
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(pdfPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(exportButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pdfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(exportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
   private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed

      int choice = buttonGroup.getSelection().getMnemonic();
      switch (choice) {
         case KeyEvent.VK_1:
            new JPEGExportAction(base, this, ExportAction.CHOICE_GRAPH);
            break;
         case KeyEvent.VK_2:
            new JPEGExportAction(base, this, ExportAction.CHOICE_STAT_REPORT);
            break;
         case KeyEvent.VK_3:
            new JPEGExportAction(base, this, ExportAction.CHOICE_FULL);
            break;
         case KeyEvent.VK_4:
            new PDFExportAction(base, this, ExportAction.CHOICE_GRAPH);
            break;
         case KeyEvent.VK_5:
//            new PDFExportAction(base, this, ExportAction.CHOICE_STAT_REPORT);
            new JTable2PdfExportAction(base,this,ExportAction.CHOICE_STAT_REPORT);
            break;
         case KeyEvent.VK_6: // always export the 3-page report
            new PDFExportAction(base, this, ExportAction.CHOICE_FULL);
            break;
         case KeyEvent.VK_7: // export detailed report with daily data
//             //add on 20091022.be
//             //v3-8 : create pdf file the same content as a print out report
//            if(base.isDailyGraphsIsNull()){
//                base.getDailyGraphs();
//            }
            new PDFExportAction(base, this, ExportAction.CHOICE_DETAILED);
            break;
         default:
            break;
      }
   }//GEN-LAST:event_exportButtonActionPerformed

   private void pdfDetailedRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pdfDetailedRadioButtonItemStateChanged
       // TODO add your handling code here:
//       if(base.isDailyGraphsIsNull()){
//           System.out.println("pdfDetailedRadioButtonItemStateChanged in");
//            base.getDailyGraphs();
//       }
//       System.out.println("pdfDetailedRadioButtonItemStateChanged out");
   }//GEN-LAST:event_pdfDetailedRadioButtonItemStateChanged
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton exportButton;
    private javax.swing.JPanel exportPanel;
    private javax.swing.JRadioButton pdfDetailedRadioButton;
    private javax.swing.JRadioButton pdfFullRadioButton;
    private javax.swing.JRadioButton pdfGraphRadioButton;
    private javax.swing.JPanel pdfPanel;
    private javax.swing.JRadioButton pdfStatRadioButton;
    // End of variables declaration//GEN-END:variables
   
}
