/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * testpdf.java
 *
 * Created on 19/08/2010, 3:09:13 PM
 */

package com.cs.canalyzer.export;

import com.cs.canalyzer.gui.Base;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author dell
 */
public class StatisticsPDFFrame extends javax.swing.JFrame {

    /** Creates new form testpdf */
    public StatisticsPDFFrame() {       
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int height = dim.height;
        jPanel1.setPreferredSize(new Dimension(680,height));
    }

    
    public void addPanel(JPanel jp){
        jPanel1.add( jp, BorderLayout.CENTER );
        
    }

    public Container getPanel(){
        this.jPanel1.setBackground(Color.white);
        return this.jPanel1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 2300));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new testpdf().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
