/*
 * CoverPage.java
 *
 * Created on 2009年1月5日, 上午11:26
 */

package com.cs.canalyzer.print.printing;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.BasicSetting;
import com.cs.canalyzer.structs.CommonValue;
import com.cs.canalyzer.structs.LeakStatistics;
import java.awt.Font;

/**
 *
 * @author  wolf
 */
public class CoverPage extends javax.swing.JPanel {

    /** Creates new form CoverPage */
    public CoverPage( final CommonValue common ) {
        this.myBasicSetting = common.getBasicSetting();
        this.myLeakStat = common.getLeakStatistics();
        
        myInit();
    }

    private void myInit() {
        initComponents();
        
        jLabelServiceName.setText( myBasicSetting.ServiceCompanyName );
        jLabelServiceAddressLine1.setText( myBasicSetting.ServiceAddressLine1 );
        jLabelServiceAddressLine2.setText( myBasicSetting.ServiceAddressLine2 );
        jLabelServiceAddressLine3.setText( myBasicSetting.ServiceAddressLine3 );
        jLabelServiceResponsible.setText( myBasicSetting.ServiceResponsiblePerson );
        jLabelServicePhone.setText( myBasicSetting.ServicePhone );
        jLabelServiceFax.setText( myBasicSetting.ServiceFax );
        jLabelServiceEmail.setText( myBasicSetting.ServiceEmail );
        jLabelServiceWeb.setText( myBasicSetting.ServiceWebpage );

        jLabelName.setText( myBasicSetting.CompanyName );
        jLabelAddressLine1.setText( myBasicSetting.AddressLine1 );
        jLabelAddressLine2.setText( myBasicSetting.AddressLine2 );
        jLabelAddressLine3.setText( myBasicSetting.AddressLine3 );
        jLabelResponsible.setText( myBasicSetting.ResponsiblePerson );
        jLabelPhone.setText( myBasicSetting.Phone );
        jLabelFax.setText( myBasicSetting.Fax );
        jLabelEmail.setText( myBasicSetting.Email );
        jLabelWeb.setText( myBasicSetting.Webpage );
        
        jLabelFrom.setText( GUIConst.DEFAULT_DATE_AND_TIME_SHORT_FORMAT( myLeakStat.getStartTime() ));
        jLabelTo.setText( GUIConst.DEFAULT_DATE_AND_TIME_SHORT_FORMAT( myLeakStat.getEndTime() ));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabelIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelAddressLine1 = new javax.swing.JLabel();
        jLabelAddressLine2 = new javax.swing.JLabel();
        jLabelAddressLine3 = new javax.swing.JLabel();
        jLabelResponsible = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelFax = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelWeb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelProject = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelServiceName = new javax.swing.JLabel();
        jLabelServiceAddressLine1 = new javax.swing.JLabel();
        jLabelServiceAddressLine2 = new javax.swing.JLabel();
        jLabelServiceAddressLine3 = new javax.swing.JLabel();
        jLabelServiceResponsible = new javax.swing.JLabel();
        jLabelServicePhone = new javax.swing.JLabel();
        jLabelServiceFax = new javax.swing.JLabel();
        jLabelServiceEmail = new javax.swing.JLabel();
        jLabelServiceWeb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFrom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanelHeader.setPreferredSize(new java.awt.Dimension(100, 520));
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelHeader.add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 90, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(DIALOG_FONT_BOLD);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        jLabel3.setText(bundle.getString("Service_Company:")); // NOI18N

        jLabelName.setFont(DIALOG_FONT_BOLD);
        jLabelName.setText("sd");

        jLabelAddressLine1.setFont(DIALOG_FONT);
        jLabelAddressLine1.setText("sd");

        jLabelAddressLine2.setFont(DIALOG_FONT);
        jLabelAddressLine2.setText("sd");

        jLabelAddressLine3.setFont(DIALOG_FONT);
        jLabelAddressLine3.setText("sd");

        jLabelResponsible.setFont(DIALOG_FONT);
        jLabelResponsible.setText("sd");

        jLabelPhone.setFont(DIALOG_FONT);
        jLabelPhone.setText("sd");

        jLabelFax.setFont(DIALOG_FONT);
        jLabelFax.setText("sd");

        jLabelEmail.setFont(DIALOG_FONT);
        jLabelEmail.setText("sd");

        jLabelWeb.setFont(DIALOG_FONT);
        jLabelWeb.setText("sd");

        jLabel5.setFont(DIALOG_FONT_BOLD_LARGE);
        jLabel5.setText(bundle.getString("Service_Company:")); // NOI18N

        jLabelProject.setFont(DIALOG_FONT_BOLD_LARGE);
        jLabelProject.setText("sd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelProject, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFax, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelResponsible, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelProject, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelResponsible, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFax, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelHeader.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 380, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(DIALOG_FONT_BOLD);
        jLabel4.setText(bundle.getString("Service_Company:")); // NOI18N

        jLabelServiceName.setFont(DIALOG_FONT_BOLD);
        jLabelServiceName.setText("sd");

        jLabelServiceAddressLine1.setFont(DIALOG_FONT);
        jLabelServiceAddressLine1.setText("sd");

        jLabelServiceAddressLine2.setFont(DIALOG_FONT);
        jLabelServiceAddressLine2.setText("sd");

        jLabelServiceAddressLine3.setFont(DIALOG_FONT);
        jLabelServiceAddressLine3.setText("sd");

        jLabelServiceResponsible.setFont(DIALOG_FONT);
        jLabelServiceResponsible.setText("sd");

        jLabelServicePhone.setFont(DIALOG_FONT);
        jLabelServicePhone.setText("sd");

        jLabelServiceFax.setFont(DIALOG_FONT);
        jLabelServiceFax.setText("sd");

        jLabelServiceEmail.setFont(DIALOG_FONT);
        jLabelServiceEmail.setText("sd");

        jLabelServiceWeb.setFont(DIALOG_FONT);
        jLabelServiceWeb.setText("sd");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelServiceWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServiceEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServiceFax, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServicePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServiceResponsible, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServiceAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServiceAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServiceAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServiceAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServiceAddressLine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServiceAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServiceResponsible, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServicePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServiceFax, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServiceEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelServiceWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelHeader.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 210));

        add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel1.setFont(DIALOG_FONT_BOLD);
        jLabel1.setText(bundle.getString("Period_of_measurement:")); // NOI18N
        jPanel1.add(jLabel1);

        jLabelFrom.setFont(DIALOG_FONT_BOLD);
        jLabelFrom.setText("       ");
        jPanel1.add(jLabelFrom);

        jLabel2.setFont(DIALOG_FONT_BOLD);
        jLabel2.setText(bundle.getString("To")); // NOI18N
        jPanel1.add(jLabel2);

        jLabelTo.setFont(DIALOG_FONT_BOLD);
        jLabelTo.setText("       ");
        jPanel1.add(jLabelTo);

        jPanel2.add(jPanel1, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    private final Font DIALOG_FONT_BOLD = new Font( "SansSerif", 1, 12 );
    private final Font DIALOG_FONT_BOLD_LARGE  = new Font( "SansSerif", 1, 14 );
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAddressLine1;
    private javax.swing.JLabel jLabelAddressLine2;
    private javax.swing.JLabel jLabelAddressLine3;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFax;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelProject;
    private javax.swing.JLabel jLabelResponsible;
    private javax.swing.JLabel jLabelServiceAddressLine1;
    private javax.swing.JLabel jLabelServiceAddressLine2;
    private javax.swing.JLabel jLabelServiceAddressLine3;
    private javax.swing.JLabel jLabelServiceEmail;
    private javax.swing.JLabel jLabelServiceFax;
    private javax.swing.JLabel jLabelServiceName;
    private javax.swing.JLabel jLabelServicePhone;
    private javax.swing.JLabel jLabelServiceResponsible;
    private javax.swing.JLabel jLabelServiceWeb;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JLabel jLabelWeb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelHeader;
    // End of variables declaration//GEN-END:variables

    private final BasicSetting myBasicSetting;
    private final LeakStatistics myLeakStat;
    
}
