/*
 * PrintDetailGraphicPreviewDialog.java
 *
 * Created on March 10, 2009, 4:27 PM
 */

package com.cs.canalyzer.print.printing;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author  bh
 */
public class PrintDetailGraphicPreviewDialog extends javax.swing.JFrame {
    
    /** Creates new form PrintDetailGraphicPreviewDialog */
    public PrintDetailGraphicPreviewDialog(Container graphicPanel) {
        initComponents();
        jPanelAddDetailGraphic.add( graphicPanel, BorderLayout.CENTER );
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( (dim.width - WIDTH ) / 2, (dim.height - HEIGHT) / 3, WIDTH, HEIGHT );   
    }
    
    public Container getPrintDetailGraphicContainer(){
        return this.jPanelAddDetailGraphic;
    }
    private final int WIDTH = 700;
    private final int HEIGHT = 520;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAddDetailGraphic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanelAddDetailGraphicLayout = new javax.swing.GroupLayout(jPanelAddDetailGraphic);
        jPanelAddDetailGraphic.setLayout(jPanelAddDetailGraphicLayout);
        jPanelAddDetailGraphicLayout.setHorizontalGroup(
            jPanelAddDetailGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanelAddDetailGraphicLayout.setVerticalGroup(
            jPanelAddDetailGraphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddDetailGraphic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddDetailGraphic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrintDetailGraphicPreviewDialog().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelAddDetailGraphic;
    // End of variables declaration//GEN-END:variables
    
}
