/*
 * CalculateSettingDialog.java
 *
 * Created on 2007年4月12日, 下午11:24
 */

package com.cs.canalyzer.gui.dialog.settings;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.gui.dialog.CommentPageDialog;
import com.cs.canalyzer.structs.BasicSetting;
import com.cs.canalyzer.structs.Texts;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author  msu
 */
public class BasicSettingDialog extends javax.swing.JFrame {
    
    /** Creates new form CalculateSettingDialog */
    public BasicSettingDialog( BasicSetting basicSetting, Texts texts ) {
        this.myBasicSetting = basicSetting;
        this.myTexts = texts;
        
        myInit();
    }
    
    private void myInit() {
        initComponents();

        if ( myBasicSetting.CompanyName.length() > 0 )
            jTextName.setText( myBasicSetting.CompanyName );
        //public String LogoFilePath = "";
    
        jTextAddressLine1.setText( myBasicSetting.AddressLine1 );
        jTextAddressLine2.setText( myBasicSetting.AddressLine2 );
        jTextAddressLine3.setText( myBasicSetting.AddressLine3 );
        jTextResponsiblePerson.setText( myBasicSetting.ResponsiblePerson );
        jTextPhone.setText( myBasicSetting.Phone );
        jTextFax.setText( myBasicSetting.Fax );
        jTextEmail.setText( myBasicSetting.Email );
        jTextWebpage.setText( myBasicSetting.Webpage );
        
        //if ( myBasicSetting.LogoFilePath.length() > 0 ) jLabelLogo.setIcon( new javax.swing.ImageIcon( myBasicSetting.LogoFilePath ));
        
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );         
        setBounds( START_X, START_Y, WIDTH, HEIGHT );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAverage = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextAddressLine1 = new javax.swing.JTextField();
        jTextAddressLine2 = new javax.swing.JTextField();
        jTextAddressLine3 = new javax.swing.JTextField();
        jTextPhone = new javax.swing.JTextField();
        jTextFax = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextWebpage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextResponsiblePerson = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonServiceCompanySetting = new javax.swing.JButton();
        jButtonServiceCompanySetting1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Basic_Information")); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Customer_Information")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(133, 40));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12));
        jLabel2.setText(bundle.getString("Company_Name")); // NOI18N

        jTextName.setFont(DIALOG_FONT);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Company_Information"))); // NOI18N

        jLabel4.setFont(DIALOG_FONT);
        jLabel4.setText(bundle.getString("Address:")); // NOI18N

        jTextAddressLine1.setFont(DIALOG_FONT);

        jTextAddressLine2.setFont(DIALOG_FONT);

        jTextAddressLine3.setFont(DIALOG_FONT);

        jTextPhone.setFont(DIALOG_FONT);

        jTextFax.setFont(DIALOG_FONT);

        jTextEmail.setFont(DIALOG_FONT);

        jTextWebpage.setFont(DIALOG_FONT);

        jLabel5.setFont(DIALOG_FONT);
        jLabel5.setText(bundle.getString("Phone:")); // NOI18N

        jLabel6.setFont(DIALOG_FONT);
        jLabel6.setText(bundle.getString("Fax:")); // NOI18N

        jLabel7.setFont(DIALOG_FONT);
        jLabel7.setText(bundle.getString("Email:")); // NOI18N

        jLabel8.setFont(DIALOG_FONT);
        jLabel8.setText(bundle.getString("Webpage:")); // NOI18N

        jLabel9.setFont(DIALOG_FONT);
        jLabel9.setText(bundle.getString("Responsible_Person:")); // NOI18N

        jTextResponsiblePerson.setFont(DIALOG_FONT);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel9)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jLabel7)
                    .add(jLabel8))
                .add(14, 14, 14)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextPhone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextResponsiblePerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextAddressLine2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextAddressLine1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextAddressLine3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextWebpage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextAddressLine1))
                .add(11, 11, 11)
                .add(jTextAddressLine2)
                .add(17, 17, 17)
                .add(jTextAddressLine3)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextResponsiblePerson))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextPhone))
                .add(24, 24, 24)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .add(19, 19, 19)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .add(22, 22, 22)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextWebpage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 412, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))))
                .add(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(jTextName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(46, 46, 46)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 50));

        jButtonOK.setFont(DIALOG_FONT);
        jButtonOK.setText(bundle.getString("OK")); // NOI18N
        jButtonOK.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(DIALOG_FONT);
        jButtonCancel.setText(bundle.getString("Cancel")); // NOI18N
        jButtonCancel.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonServiceCompanySetting.setFont(DIALOG_FONT);
        jButtonServiceCompanySetting.setText(bundle.getString("Service_Company_Setting")); // NOI18N
        jButtonServiceCompanySetting.setToolTipText(bundle.getString("Click_to_select_an_image_file_as_the_company_logo._The_logo_will_appear_in_printed_reports_with_company_information.")); // NOI18N
        jButtonServiceCompanySetting.setPreferredSize(new java.awt.Dimension(120, 23));
        jButtonServiceCompanySetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiceCompanySettingActionPerformed(evt);
            }
        });

        jButtonServiceCompanySetting1.setFont(DIALOG_FONT);
        jButtonServiceCompanySetting1.setText(bundle.getString("Write_Comment_Page")); // NOI18N
        jButtonServiceCompanySetting1.setToolTipText(bundle.getString("Click_to_select_an_image_file_as_the_company_logo._The_logo_will_appear_in_printed_reports_with_company_information.")); // NOI18N
        jButtonServiceCompanySetting1.setPreferredSize(new java.awt.Dimension(120, 23));
        jButtonServiceCompanySetting1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServiceCompanySetting1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(63, 63, 63)
                .add(jButtonServiceCompanySetting1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonServiceCompanySetting, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(125, 125, 125))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonServiceCompanySetting, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonServiceCompanySetting1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {
            myBasicSetting.CompanyName = jTextName.getText();
            
            myBasicSetting.AddressLine1 = jTextAddressLine1.getText();
            myBasicSetting.AddressLine2 = jTextAddressLine2.getText();
            myBasicSetting.AddressLine3 = jTextAddressLine3.getText();
            myBasicSetting.ResponsiblePerson = jTextResponsiblePerson.getText();
            myBasicSetting.Phone = jTextPhone.getText();
            myBasicSetting.Fax = jTextFax.getText();
            myBasicSetting.Email = jTextEmail.getText();
            myBasicSetting.Webpage = jTextWebpage.getText();

        } catch ( Exception e ) {}
        
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

private void jButtonServiceCompanySettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiceCompanySettingActionPerformed
    ServiceCompanySettingDialog dlg = new ServiceCompanySettingDialog( myBasicSetting );
    dlg.setModal( true );
    dlg.setVisible( true );
}//GEN-LAST:event_jButtonServiceCompanySettingActionPerformed

private void jButtonServiceCompanySetting1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServiceCompanySetting1ActionPerformed
    CommentPageDialog commentDlg = new CommentPageDialog( myTexts );
    commentDlg.setVisible( true );    
}//GEN-LAST:event_jButtonServiceCompanySetting1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSettingDialog().setVisible(true);
            }
        });
    }*/
    
    private final int START_X = 200;
    private final int START_Y = 200;
    private final int WIDTH = 600;
    private final int HEIGHT = 600;
    
    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAverage;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonServiceCompanySetting;
    private javax.swing.JButton jButtonServiceCompanySetting1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextAddressLine1;
    private javax.swing.JTextField jTextAddressLine2;
    private javax.swing.JTextField jTextAddressLine3;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhone;
    private javax.swing.JTextField jTextResponsiblePerson;
    private javax.swing.JTextField jTextWebpage;
    // End of variables declaration//GEN-END:variables
    
    private BasicSetting myBasicSetting;
    private Texts myTexts;
    
}
