/*
 * CalculateSettingDialog.java
 *
 * Created on 2007年4月12日, 下午11:24
 */

package com.cs.canalyzer.gui.dialog.settings;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.CommonValue;
import com.cs.canalyzer.structs.LeakStatistics;
import java.awt.EventQueue;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author  msu
 */
public class CalculateSettingDialog extends javax.swing.JFrame {
    
    /** Creates new form CalculateSettingDialog */
    public CalculateSettingDialog( CommonValue common ) {
        this.theCommonValue = common;
        this.myLeakStat = common.getLeakStatistics();
        //tempLeakStat = new LeakStatistics( common.getDataBase() );
        
        myInit();
    }
    
    private void myInit() {
        initComponents();

        buttonGroupCalculateBy.add( jRadioByFlow );
        buttonGroupCalculateBy.add( jRadioByPower );
        buttonGroupCalculateBy.add( jRadioBySpec );
        
        initFields();
        
        setIconImage( new ImageIcon( getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );         
        setBounds( START_X, START_Y, WIDTH, HEIGHT );
    }
    
    private void initFields() {
//        switch ( myLeakStat.calculationType ) {
//            case LeakStatistics.CALCULATION_BASED_ON_POWER: jRadioByPower.setSelected( true ); break;
//            case LeakStatistics.CALCULATION_BASED_ON_FLOW: jRadioByFlow.setSelected( true ); break;
//            case LeakStatistics.CALCULATION_BASED_ON_COMPRESSOR_SPEC: jRadioBySpec.setSelected( true ); break;
//            default: jRadioByFlow.setSelected( true );
//        }

        if ( myLeakStat.fullLoadCurrent != LeakStatistics.DEFAULT_COSP_PARAMETER ) 
            jTextFullLoadCurrent.setText( String.valueOf( myLeakStat.fullLoadCurrent ));
        if ( myLeakStat.noLoadCurrent != LeakStatistics.DEFAULT_COSP_PARAMETER ) 
            jTextNoLoadCurrent.setText( String.valueOf( myLeakStat.noLoadCurrent ));
        if ( myLeakStat.fullLoadCosP != LeakStatistics.DEFAULT_COSP_PARAMETER ) 
            jTextFullLoadCosP.setText( String.valueOf( myLeakStat.fullLoadCosP ));
        if ( myLeakStat.noLoadCosP != LeakStatistics.DEFAULT_COSP_PARAMETER ) 
            jTextNoLoadCosP.setText( String.valueOf( myLeakStat.noLoadCosP ));
        if ( myLeakStat.fullLoadCurrentThreshold != LeakStatistics.DEFAULT_COSP_PARAMETER ) 
            jTextFullLoadCurrentThreshold.setText( String.valueOf( myLeakStat.fullLoadCurrentThreshold ));
        if ( myLeakStat.noLoadCurrentThreshold != LeakStatistics.DEFAULT_COSP_PARAMETER ) 
            jTextNoLoadCurrentThreshold.setText( String.valueOf( myLeakStat.noLoadCurrentThreshold ));
        
        jTextVoltage.setText( String.valueOf( myLeakStat.voltage ));
        jTextCostPerKwh.setText( String.valueOf( myLeakStat.costPerKwh ));
        jTextPowerConsumptionCurrency.setText( myLeakStat.currencyPowerConsumption );
        
        jTextCostPerM3.setText( String.valueOf( myLeakStat.energyCostPerM3 ));
        //jTextFlowConsumptionCurrency.setText( myLeakStat.currencyEnergyCost ); // --- removed, combined with power consumption currency
        jLabelCurrency.setText( myLeakStat.currencyPowerConsumption );
        
        jTextFullLoadPowerConsumption.setText( String.valueOf( myLeakStat.fullLoadPowerConsumption ));
        jTextNoLoadPowerConsumption.setText( String.valueOf( myLeakStat.noLoadPowerConsumption ));
        jTextFullLoadOperationTime.setText( String.format( "%5.2f", myLeakStat.fullLoadOperationTime * 100 ));
        jTextNoLoadOperationTime.setText( String.format( "%5.2f", myLeakStat.noLoadOperationTime * 100 ));
        jTextOperationalHourPerYear.setText( String.valueOf( myLeakStat.operateHourPerYear ));
        
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCalculateBy = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextNoLoadPowerConsumption = new javax.swing.JTextField();
        jTextFullLoadPowerConsumption = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextNoLoadOperationTime = new javax.swing.JTextField();
        jTextFullLoadOperationTime = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextOperationalHourPerYear = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextCostPerM3 = new javax.swing.JTextField();
        jLabelCurrency = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFullLoadCurrent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextVoltage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFullLoadCosP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextNoLoadCurrent = new javax.swing.JTextField();
        jTextNoLoadCosP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextNoLoadCurrentThreshold = new javax.swing.JTextField();
        jTextFullLoadCurrentThreshold = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextCostPerKwh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextPowerConsumptionCurrency = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jRadioByPower = new javax.swing.JRadioButton();
        jRadioByFlow = new javax.swing.JRadioButton();
        jRadioBySpec = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Calculation_Setting")); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Calculation_Setting")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(133, 40));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        jButtonOK.setFont(DIALOG_FONT);
        jButtonOK.setText(bundle.getString("OK")); // NOI18N
        jButtonOK.setPreferredSize(new java.awt.Dimension(70, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOK);

        jButtonCancel.setFont(DIALOG_FONT);
        jButtonCancel.setText(bundle.getString("Cancel")); // NOI18N
        jButtonCancel.setPreferredSize(new java.awt.Dimension(70, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Compressor_Settings"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, DIALOG_FONT, new java.awt.Color(5, 176, 117))); // NOI18N

        jLabel15.setFont(DIALOG_FONT);
        jLabel15.setText(bundle.getString("Full_load:")); // NOI18N

        jLabel16.setFont(DIALOG_FONT);
        jLabel16.setText(bundle.getString("No_load:")); // NOI18N

        jTextNoLoadPowerConsumption.setFont(DIALOG_FONT);

        jTextFullLoadPowerConsumption.setFont(DIALOG_FONT);

        jLabel17.setFont(DIALOG_FONT);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(bundle.getString("<html>Power_Consumption<br>(kWh)</html>")); // NOI18N

        jLabel18.setFont(DIALOG_FONT);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(bundle.getString("<html>Operation_Time<br>(%)</html>")); // NOI18N

        jTextNoLoadOperationTime.setFont(DIALOG_FONT);

        jTextFullLoadOperationTime.setFont(DIALOG_FONT);

        jLabel19.setFont(DIALOG_FONT);
        jLabel19.setText(bundle.getString("Operational_Hour_per_Year:")); // NOI18N

        jTextOperationalHourPerYear.setFont(DIALOG_FONT);

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jLabel19)
                        .add(21, 21, 21)
                        .add(jTextOperationalHourPerYear, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .add(16, 16, 16))
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(jLabel15)
                                .add(38, 38, 38)
                                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextNoLoadPowerConsumption, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextFullLoadPowerConsumption, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jLabel16)
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(77, 77, 77)
                                .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextNoLoadOperationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .add(jLabel18)
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(jTextFullLoadOperationTime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .add(16, 16, 16)))))
                .add(418, 418, 418))
        );

        jPanel7Layout.linkSize(new java.awt.Component[] {jTextFullLoadOperationTime, jTextFullLoadPowerConsumption, jTextNoLoadOperationTime}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(jLabel18))
                .add(20, 20, 20)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(jTextFullLoadPowerConsumption, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFullLoadOperationTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(jTextNoLoadPowerConsumption, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextNoLoadOperationTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel19)
                    .add(jTextOperationalHourPerYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Flow_Consumption_Settings"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, DIALOG_FONT, new java.awt.Color(5, 176, 117))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 80));

        jLabel13.setFont(DIALOG_FONT);
        jLabel13.setText(bundle.getString("Energy_Cost_per_m3")); // NOI18N

        jTextCostPerM3.setFont(DIALOG_FONT);
        jTextCostPerM3.setText("0.10");

        jLabelCurrency.setFont(DIALOG_FONT);
        jLabelCurrency.setForeground(new java.awt.Color(153, 0, 51));
        jLabelCurrency.setText(bundle.getString("Euro")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel13)
                .add(27, 27, 27)
                .add(jTextCostPerM3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(jLabelCurrency)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(jTextCostPerM3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelCurrency))
                .add(32, 32, 32))
        );

        jPanel4.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Power_Consumption_Settings"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, DIALOG_FONT, new java.awt.Color(5, 176, 117))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(26, 200));

        jLabel2.setFont(DIALOG_FONT);
        jLabel2.setText(bundle.getString("cos_ρ:")); // NOI18N

        jTextFullLoadCurrent.setFont(DIALOG_FONT);

        jLabel3.setFont(DIALOG_FONT);
        jLabel3.setText(bundle.getString("Supply_Voltage:")); // NOI18N

        jTextVoltage.setFont(DIALOG_FONT);
        jTextVoltage.setText("380");

        jLabel4.setFont(DIALOG_FONT);
        jLabel4.setText(bundle.getString("V")); // NOI18N

        jTextFullLoadCosP.setFont(DIALOG_FONT);

        jLabel8.setFont(DIALOG_FONT);
        jLabel8.setText(bundle.getString("Full_load:")); // NOI18N

        jLabel9.setFont(DIALOG_FONT);
        jLabel9.setText(bundle.getString("No_load:")); // NOI18N

        jTextNoLoadCurrent.setFont(DIALOG_FONT);

        jTextNoLoadCosP.setFont(DIALOG_FONT);

        jLabel10.setFont(DIALOG_FONT);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(bundle.getString("Current_(A)")); // NOI18N

        jLabel11.setFont(DIALOG_FONT);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(bundle.getString("cos_ρ:")); // NOI18N

        jLabel12.setFont(DIALOG_FONT);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(bundle.getString("Threshold")); // NOI18N

        jTextNoLoadCurrentThreshold.setFont(DIALOG_FONT);

        jTextFullLoadCurrentThreshold.setFont(DIALOG_FONT);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel3)
                        .add(42, 42, 42)
                        .add(jTextVoltage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8)
                            .add(jLabel9))
                        .add(31, 31, 31)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextFullLoadCurrent, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jTextNoLoadCurrent))))
                .add(14, 14, 14)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(5, 5, 5)
                                .add(jLabel11))
                            .add(jTextNoLoadCosP)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jTextFullLoadCosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextNoLoadCurrentThreshold, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .add(jTextFullLoadCurrentThreshold, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .add(jLabel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel10))
                        .add(14, 14, 14)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(jTextFullLoadCurrent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFullLoadCurrentThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFullLoadCosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jTextNoLoadCurrent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextNoLoadCosP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextNoLoadCurrentThreshold, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel11)
                        .add(jLabel12)))
                .add(29, 29, 29)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jTextVoltage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("Cost_Settings"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, DIALOG_FONT, new java.awt.Color(5, 176, 117))); // NOI18N

        jLabel5.setFont(DIALOG_FONT);
        jLabel5.setText(bundle.getString("Energy_Cost_per_kWh:")); // NOI18N

        jTextCostPerKwh.setFont(DIALOG_FONT);
        jTextCostPerKwh.setText("0.10");

        jLabel6.setFont(DIALOG_FONT);
        jLabel6.setText(bundle.getString("Currency:")); // NOI18N

        jTextPowerConsumptionCurrency.setFont(DIALOG_FONT);
        jTextPowerConsumptionCurrency.setText(bundle.getString("Euro")); // NOI18N
        jTextPowerConsumptionCurrency.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPowerConsumptionCurrencyKeyTyped(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel10Layout = new org.jdesktop.layout.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jLabel5))
                .add(19, 19, 19)
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextPowerConsumptionCurrency)
                    .add(jTextCostPerKwh, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel10Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextCostPerKwh, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jPanel10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jTextPowerConsumptionCurrency, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9, java.awt.BorderLayout.WEST);

        jPanel5.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel7.setFont(DIALOG_FONT);
        jLabel7.setForeground(new java.awt.Color(5, 176, 117));
        jLabel7.setText(bundle.getString("Energy_Cost_Calculated_By:")); // NOI18N
        jPanel6.add(jLabel7);

        jRadioByPower.setFont(DIALOG_FONT);
        jRadioByPower.setText(bundle.getString("Power_Consumption")); // NOI18N
        jRadioByPower.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioByPower.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel6.add(jRadioByPower);

        jRadioByFlow.setFont(DIALOG_FONT);
        jRadioByFlow.setText(bundle.getString("Flow_Consumption")); // NOI18N
        jRadioByFlow.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioByFlow.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel6.add(jRadioByFlow);

        jRadioBySpec.setFont(DIALOG_FONT);
        jRadioBySpec.setText(bundle.getString("Compressor_Specification")); // NOI18N
        jRadioBySpec.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioBySpec.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel6.add(jRadioBySpec);

        jPanel5.add(jPanel6, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPowerConsumptionCurrencyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPowerConsumptionCurrencyKeyTyped
        EventQueue.invokeLater( new Runnable() {
            public void run() {
                jLabelCurrency.setText( jTextPowerConsumptionCurrency.getText() );
            }
        });
    }//GEN-LAST:event_jTextPowerConsumptionCurrencyKeyTyped

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {
            
//            if ( jRadioByFlow.isSelected() ) 
//                myLeakStat.calculationType = LeakStatistics.CALCULATION_BASED_ON_FLOW;
//            else if ( jRadioByPower.isSelected() ) 
//                myLeakStat.calculationType = LeakStatistics.CALCULATION_BASED_ON_POWER;
//            else if ( jRadioBySpec.isSelected() ) 
//                myLeakStat.calculationType = LeakStatistics.CALCULATION_BASED_ON_COMPRESSOR_SPEC;
            
            getCosPs();

            myLeakStat.voltage = Float.valueOf( GUIConst.VerifyString( jTextVoltage.getText() ));
            myLeakStat.costPerKwh = Float.valueOf( GUIConst.VerifyString( jTextCostPerKwh.getText() ));
            myLeakStat.currencyPowerConsumption = jTextPowerConsumptionCurrency.getText();
            
            myLeakStat.energyCostPerM3 = Float.valueOf( GUIConst.VerifyString( jTextCostPerM3.getText() ));
            //myLeakStat.currencyEnergyCost = jTextFlowConsumptionCurrency.getText();
            myLeakStat.currencyEnergyCost = jTextPowerConsumptionCurrency.getText();
            
            myLeakStat.fullLoadPowerConsumption = Float.valueOf( GUIConst.VerifyString( jTextFullLoadPowerConsumption.getText() ));
            myLeakStat.noLoadPowerConsumption = Float.valueOf( GUIConst.VerifyString( jTextNoLoadPowerConsumption.getText() ));
            myLeakStat.fullLoadOperationTime = Float.valueOf( GUIConst.VerifyString( jTextFullLoadOperationTime.getText() )) / 100;
            myLeakStat.noLoadOperationTime = Float.valueOf( GUIConst.VerifyString( jTextNoLoadOperationTime.getText() )) / 100;
            if ( myLeakStat.fullLoadOperationTime > 1 || myLeakStat.fullLoadOperationTime < 0 ||  
                    myLeakStat.noLoadOperationTime > 1 || myLeakStat.noLoadOperationTime < 0 ||
                    myLeakStat.fullLoadOperationTime + myLeakStat.noLoadOperationTime > 1 ) {
                JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<html>Full_load_and_no_load_operation_time_pecentage_must_be_a_number_between_0_~_1.<br>") +
                        java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<br>And_the_sum_of_those_2_must_be_no_larger_than_1.<br><br></html>")  );
                return;
            }
            
            myLeakStat.operateHourPerYear = Float.valueOf( GUIConst.VerifyString( jTextOperationalHourPerYear.getText() ));
            
            myLeakStat.triggerCalculate();
            //theCommonValue.setLeakStatistics( tempLeakStat );     
            theCommonValue.setCanStatistic(true);
            dispose();
        } catch ( Exception e ) {
            JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Please_enter_valid_numbers.") );
        }
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void getCosPs() {
        try {
            if ( jTextFullLoadCurrent.getText().length() > 0 )
                myLeakStat.fullLoadCurrent = Float.valueOf( GUIConst.VerifyString( jTextFullLoadCurrent.getText() ));
            else
                myLeakStat.fullLoadCurrent = LeakStatistics.DEFAULT_COSP_PARAMETER;
            
            if ( jTextNoLoadCurrent.getText().length() > 0 )
                myLeakStat.noLoadCurrent = Float.valueOf( GUIConst.VerifyString( jTextNoLoadCurrent.getText() ));
            else
                myLeakStat.noLoadCurrent = LeakStatistics.DEFAULT_COSP_PARAMETER;

            if ( jTextFullLoadCosP.getText().length() > 0 )
                myLeakStat.fullLoadCosP = Float.valueOf( GUIConst.VerifyString( jTextFullLoadCosP.getText() ));
            else
                myLeakStat.fullLoadCosP = LeakStatistics.DEFAULT_COSP_PARAMETER;

            if ( jTextNoLoadCosP.getText().length() > 0 )
                myLeakStat.noLoadCosP = Float.valueOf( GUIConst.VerifyString( jTextNoLoadCosP.getText() ));
            else
                myLeakStat.noLoadCosP = LeakStatistics.DEFAULT_COSP_PARAMETER;

            if ( jTextFullLoadCurrentThreshold.getText().length() > 0 )
                myLeakStat.fullLoadCurrentThreshold = Float.valueOf( GUIConst.VerifyString( jTextFullLoadCurrentThreshold.getText() ));
            else
                myLeakStat.fullLoadCurrentThreshold = LeakStatistics.DEFAULT_COSP_PARAMETER;

            if ( jTextNoLoadCurrentThreshold.getText().length() > 0 )
                myLeakStat.noLoadCurrentThreshold = Float.valueOf( GUIConst.VerifyString( jTextNoLoadCurrentThreshold.getText() ));
            else
                myLeakStat.noLoadCurrentThreshold = LeakStatistics.DEFAULT_COSP_PARAMETER;

        } catch ( Exception e ) {
            
        }
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSettingDialog().setVisible(true);
            }
        });
    }*/
    
    private final int START_X = 200;
    private final int START_Y = 100;
    private final int WIDTH = 700;
    private final int HEIGHT = 470;
    
    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCalculateBy;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCurrency;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioByFlow;
    private javax.swing.JRadioButton jRadioByPower;
    private javax.swing.JRadioButton jRadioBySpec;
    private javax.swing.JTextField jTextCostPerKwh;
    private javax.swing.JTextField jTextCostPerM3;
    private javax.swing.JTextField jTextFullLoadCosP;
    private javax.swing.JTextField jTextFullLoadCurrent;
    private javax.swing.JTextField jTextFullLoadCurrentThreshold;
    private javax.swing.JTextField jTextFullLoadOperationTime;
    private javax.swing.JTextField jTextFullLoadPowerConsumption;
    private javax.swing.JTextField jTextNoLoadCosP;
    private javax.swing.JTextField jTextNoLoadCurrent;
    private javax.swing.JTextField jTextNoLoadCurrentThreshold;
    private javax.swing.JTextField jTextNoLoadOperationTime;
    private javax.swing.JTextField jTextNoLoadPowerConsumption;
    private javax.swing.JTextField jTextOperationalHourPerYear;
    private javax.swing.JTextField jTextPowerConsumptionCurrency;
    private javax.swing.JTextField jTextVoltage;
    // End of variables declaration//GEN-END:variables
    

    private CommonValue theCommonValue;
    private LeakStatistics myLeakStat;
    //private LeakStatistics tempLeakStat;  // for assigning temperary value. will be discard when cancel
    
}
