/*
 * CalculateSettingDialog.java
 *
 * Created on 2007年4月12日, 下午11:24
 */

package com.cs.canalyzer.gui.dialog.settings;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.ViewOptions;
import com.cs.canalyzer.structs.CommonValue;
import com.cs.canalyzer.structs.Texts;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author  msu
 */
public class ChangeTextDialog extends javax.swing.JFrame {
    
    /** Creates new form CalculateSettingDialog */
    public ChangeTextDialog( CommonValue common) {
        this.theCommonValue = common;
        this.myTexts = common.getTexts();
        
        myInit();
    }
    
    private void myInit() {
        initComponents();

        try {
            setLegends();
            
            jTextTitle.setText( myTexts.Title );
            ViewOptions viewOptions = theCommonValue.getViewOptions();
            jLabelUnit1.setText( myTexts.ValueAxises[0] + " (" + viewOptions.yUnits[0] + ")" );
            jLabelUnit2.setText( myTexts.ValueAxises[1] + " (" + viewOptions.yUnits[1] + ")" );
            jLabelUnit3.setText( myTexts.ValueAxises[2] + " (" + viewOptions.yUnits[2] + ")" );
            jLabelUnit4.setText( myTexts.ValueAxises[3] + " (" + viewOptions.yUnits[3] + ")" );
            //jLabelLegend1.setText( theCommonValue.getViewOptions().)
            
        } catch ( Exception e ) {}
        
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );         
        setBounds( START_X, START_Y, WIDTH, HEIGHT );
    }
    
    private void setLegends() {
        jTextLegend1.setText( myTexts.Legends[0] );
        jTextLegend2.setText( myTexts.Legends[1] );
        jTextLegend3.setText( myTexts.Legends[2] );
        jTextLegend4.setText( myTexts.Legends[3] );
        jTextLegend5.setText( myTexts.Legends[4] );
        jTextLegend6.setText( myTexts.Legends[5] );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAverage = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextYAxis1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextYAxis2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelUnit1 = new javax.swing.JLabel();
        jLabelUnit2 = new javax.swing.JLabel();
        jLabelLegend1 = new javax.swing.JLabel();
        jTextLegend1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelLegend2 = new javax.swing.JLabel();
        jTextLegend2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelLegend3 = new javax.swing.JLabel();
        jTextLegend3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelLegend4 = new javax.swing.JLabel();
        jTextLegend4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabelLegend5 = new javax.swing.JLabel();
        jLabelLegend6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextLegend5 = new javax.swing.JTextField();
        jTextLegend6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabelUnit3 = new javax.swing.JLabel();
        jTextYAxis3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabelUnit4 = new javax.swing.JLabel();
        jTextYAxis4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Change_Text")); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Change_Texts")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(133, 40));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(DIALOG_FONT);
        jLabel2.setText(bundle.getString("Title:")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextTitle.setFont(DIALOG_FONT);
        jTextTitle.setText(bundle.getString("Compress_Air_Analyzer")); // NOI18N
        jPanel1.add(jTextTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 380, -1));

        jLabel5.setFont(DIALOG_FONT);
        jLabel5.setText(bundle.getString("Value_Axis_1:")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTextYAxis1.setFont(DIALOG_FONT);
        jPanel1.add(jTextYAxis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 300, -1));

        jLabel6.setFont(DIALOG_FONT);
        jLabel6.setText(bundle.getString("Value_Axis_2:")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jTextYAxis2.setFont(DIALOG_FONT);
        jPanel1.add(jTextYAxis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 300, -1));

        jLabel7.setFont(DIALOG_FONT);
        jLabel7.setText(bundle.getString("Legend_1:")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabelUnit1.setFont(DIALOG_FONT);
        jLabelUnit1.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(jLabelUnit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, 20));

        jLabelUnit2.setFont(DIALOG_FONT);
        jLabelUnit2.setForeground(new java.awt.Color(0, 153, 0));
        jLabelUnit2.setText(" ");
        jPanel1.add(jLabelUnit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 20));

        jLabelLegend1.setFont(DIALOG_FONT);
        jLabelLegend1.setText(" ");
        jPanel1.add(jLabelLegend1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        jTextLegend1.setFont(DIALOG_FONT);
        jPanel1.add(jTextLegend1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 300, -1));

        jLabel8.setFont(DIALOG_FONT);
        jLabel8.setText(bundle.getString("Legend_2:")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabelLegend2.setFont(DIALOG_FONT);
        jLabelLegend2.setText(" ");
        jPanel1.add(jLabelLegend2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, -1));

        jTextLegend2.setFont(DIALOG_FONT);
        jPanel1.add(jTextLegend2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 300, -1));

        jLabel9.setFont(DIALOG_FONT);
        jLabel9.setText(bundle.getString("Legend_3:")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabelLegend3.setFont(DIALOG_FONT);
        jLabelLegend3.setText(" ");
        jPanel1.add(jLabelLegend3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 120, -1));

        jTextLegend3.setFont(DIALOG_FONT);
        jPanel1.add(jTextLegend3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 300, -1));

        jLabel10.setFont(DIALOG_FONT);
        jLabel10.setText(bundle.getString("Legend_4:")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabelLegend4.setFont(DIALOG_FONT);
        jLabelLegend4.setText(" ");
        jPanel1.add(jLabelLegend4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 120, -1));

        jTextLegend4.setFont(DIALOG_FONT);
        jPanel1.add(jTextLegend4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 300, -1));

        jLabel11.setFont(DIALOG_FONT);
        jLabel11.setText(bundle.getString("Legend_5:")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabelLegend5.setFont(DIALOG_FONT);
        jLabelLegend5.setText(" ");
        jPanel1.add(jLabelLegend5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 120, -1));

        jLabelLegend6.setFont(DIALOG_FONT);
        jLabelLegend6.setText(" ");
        jPanel1.add(jLabelLegend6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 120, -1));

        jLabel12.setFont(DIALOG_FONT);
        jLabel12.setText(bundle.getString("Legend_6:")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jTextLegend5.setFont(DIALOG_FONT);
        jPanel1.add(jTextLegend5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 300, -1));

        jTextLegend6.setFont(DIALOG_FONT);
        jPanel1.add(jTextLegend6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 300, -1));

        jLabel13.setFont(DIALOG_FONT);
        jLabel13.setText(bundle.getString("Value_Axis_3:")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabelUnit3.setFont(DIALOG_FONT);
        jLabelUnit3.setForeground(new java.awt.Color(0, 153, 0));
        jLabelUnit3.setText(" ");
        jPanel1.add(jLabelUnit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 90, 20));

        jTextYAxis3.setFont(DIALOG_FONT);
        jPanel1.add(jTextYAxis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 300, -1));

        jLabel14.setFont(DIALOG_FONT);
        jLabel14.setText(bundle.getString("Value_Axis_4:")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabelUnit4.setFont(DIALOG_FONT);
        jLabelUnit4.setForeground(new java.awt.Color(0, 153, 0));
        jLabelUnit4.setText(" ");
        jPanel1.add(jLabelUnit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 90, 20));

        jTextYAxis4.setFont(DIALOG_FONT);
        jPanel1.add(jTextYAxis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 300, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));

        jButtonOK.setFont(DIALOG_FONT);
        jButtonOK.setText(bundle.getString("OK")); // NOI18N
        jButtonOK.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(DIALOG_FONT);
        jButtonCancel.setText(bundle.getString("Cancel")); // NOI18N
        jButtonCancel.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {
            myTexts.Title = jTextTitle.getText();
            getLegends();

            String s = jTextYAxis1.getText();
            if ( s.length() > 0 )
                myTexts.ValueAxises[0] = s;
            s = jTextYAxis2.getText();
            if ( s.length() > 0 )
                myTexts.ValueAxises[1] = s;
            s = jTextYAxis3.getText();
            if ( s.length() > 0 )
                myTexts.ValueAxises[2] = s;
            s = jTextYAxis4.getText();
            if ( s.length() > 0 )
                myTexts.ValueAxises[3] = s;
        } catch ( Exception e ) {}
        
        theCommonValue.setTexts( myTexts );
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void getLegends() {
        myTexts.Legends[0] =  jTextLegend1.getText();
        myTexts.Legends[1] =  jTextLegend2.getText();
        myTexts.Legends[2] =  jTextLegend3.getText();
        myTexts.Legends[3] =  jTextLegend4.getText();
        myTexts.Legends[4] =  jTextLegend5.getText();
        myTexts.Legends[5] =  jTextLegend6.getText();
    }
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSettingDialog().setVisible(true);
            }
        });
    }*/
    
    private final int START_X = 200;
    private final int START_Y = 100;
    private final int WIDTH = 580;
    private final int HEIGHT = 600;
    
    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAverage;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLegend1;
    private javax.swing.JLabel jLabelLegend2;
    private javax.swing.JLabel jLabelLegend3;
    private javax.swing.JLabel jLabelLegend4;
    private javax.swing.JLabel jLabelLegend5;
    private javax.swing.JLabel jLabelLegend6;
    private javax.swing.JLabel jLabelUnit1;
    private javax.swing.JLabel jLabelUnit2;
    private javax.swing.JLabel jLabelUnit3;
    private javax.swing.JLabel jLabelUnit4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextLegend1;
    private javax.swing.JTextField jTextLegend2;
    private javax.swing.JTextField jTextLegend3;
    private javax.swing.JTextField jTextLegend4;
    private javax.swing.JTextField jTextLegend5;
    private javax.swing.JTextField jTextLegend6;
    private javax.swing.JTextField jTextTitle;
    private javax.swing.JTextField jTextYAxis1;
    private javax.swing.JTextField jTextYAxis2;
    private javax.swing.JTextField jTextYAxis3;
    private javax.swing.JTextField jTextYAxis4;
    // End of variables declaration//GEN-END:variables
    
    private CommonValue theCommonValue;
    private Texts myTexts;
}
