/*
 * SelectTimePeriodDialog.java
 *
 * Created on 2007年6月13日, 下午2:33
 */

package com.cs.canalyzer.gui.dialog.settings;

import com.cs.canalyzer.gui.GUIConst;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  msu
 */
public class SelectTimePeriodDialog extends javax.swing.JDialog {
    
    /** Creates new form SelectTimePeriodDialog */
    public SelectTimePeriodDialog( Calendar initStartTime, Calendar initEndTime, boolean selectEndTime ) {
        this.startTime = initStartTime;
        this.endTime = initEndTime;
        this.selectEndTime = selectEndTime;
        if ( startTime == null ) startTime = Calendar.getInstance();
        if ( endTime == null ) endTime = Calendar.getInstance();
        
        
        myInit();
    }
    
    private void myInit() {
        initComponents();
        
        this.initStartDate = Calendar.getInstance();
        this.initEndDate = Calendar.getInstance();
        initStartDate.setTimeInMillis( startTime.getTimeInMillis() );
        initStartDate.set( Calendar.HOUR_OF_DAY, 0 );
        initStartDate.set( Calendar.MINUTE, 0 );
        initStartDate.set( Calendar.SECOND, 0 );
        initEndDate.setTimeInMillis( endTime.getTimeInMillis() );
        initEndDate.set( Calendar.HOUR_OF_DAY, 23 );
        initEndDate.set( Calendar.MINUTE, 59 );
        initEndDate.set( Calendar.SECOND, 59 );
        
        numModelStartHour = new SpinnerNumberModel( 0, 0, 23, 1 );
        jSpinnerStartHour.setModel( numModelStartHour );
        numModelEndHour = new SpinnerNumberModel( 0, 0, 23, 1 );
        jSpinnerEndHour.setModel( numModelEndHour );
//        numModelStartMinute = new SpinnerNumberModel( 0, 0, 59, 1 );
//        jSpinnerStartMinute.setModel( numModelStartMinute );
//        numModelEndMinute = new SpinnerNumberModel( 0, 0, 59, 1 );
//        jSpinnerEndMinute.setModel( numModelEndMinute );
//        numModelStartSecond = new SpinnerNumberModel( 0, 0, 59, 1 );
//        jSpinnerStartSecond.setModel( numModelStartSecond );
//        numModelEndSecond = new SpinnerNumberModel( 0, 0, 59, 1 );
//        jSpinnerEndSecond.setModel( numModelEndSecond );
        
        initTimeFields();
        
        jCheckSelectEndTime.setSelected( selectEndTime );
        setEndTimeFields();
        
        //pack();
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( (dim.width - WIDTH) / 2, (dim.height - HEIGHT) / 4, WIDTH, HEIGHT );
        
    }
    
    private void initTimeFields() {
        try {
            Timestamp stime, etime;
            
            stime = new Timestamp( startTime.getTimeInMillis() );
            jLabelStart.setText( GUIConst.DEFAULT_DATE_AND_TIME_FORMAT( stime ));
            jXDatePickerStart.setDate( startTime.getTime() );
            numModelStartHour.setValue( startTime.get( Calendar.HOUR_OF_DAY ) );
            //numModelStartMinute.setValue( startTime.get( Calendar.MINUTE ) );
            //numModelStartSecond.setValue( startTime.get( Calendar.SECOND ) );
       
            etime = new Timestamp( endTime.getTimeInMillis() );
            jLabelEnd.setText( GUIConst.DEFAULT_DATE_AND_TIME_FORMAT( etime ));
            jXDatePickerEnd.setDate( endTime.getTime() );
            numModelEndHour.setValue( endTime.get( Calendar.HOUR_OF_DAY ) );
            //numModelEndMinute.setValue( endTime.get( Calendar.MINUTE ) );
            //numModelEndSecond.setValue( endTime.get( Calendar.SECOND ) );

        } catch ( Exception e ) {
            System.out.println( "initTimeFields: " + e.getMessage() );
        }
        
    }
    
    private void setEndTimeFields() {
        jLabelEndTimeDate.setVisible( selectEndTime );
        jLabelEndTimeHour.setVisible( selectEndTime );
        jLabelTo.setVisible( selectEndTime );
        jSpinnerEndHour.setVisible( selectEndTime );
        jXDatePickerEnd.setVisible( selectEndTime );
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelPeriod = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelEndTimeHour = new javax.swing.JLabel();
        jLabelEndTimeDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();
        jLabelStart = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerEndHour = new javax.swing.JSpinner();
        jSpinnerStartHour = new javax.swing.JSpinner();
        jXDatePickerStart = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerEnd = new org.jdesktop.swingx.JXDatePicker();
        jCheckSelectEndTime = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Time_Option"));
        setResizable(false);
        jPanelPeriod.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12));
        jLabel2.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Current_selected_start_and_end_time:"));
        jPanelPeriod.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12));
        jLabel3.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Which_period_you_want_to_select?"));
        jPanelPeriod.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabelEndTimeHour.setFont(new java.awt.Font("SansSerif", 0, 12));
        jLabelEndTimeHour.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Hour"));
        jPanelPeriod.add(jLabelEndTimeHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabelEndTimeDate.setFont(new java.awt.Font("SansSerif", 0, 12));
        jLabelEndTimeDate.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Date"));
        jPanelPeriod.add(jLabelEndTimeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12));
        jLabel7.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Hour"));
        jPanelPeriod.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12));
        jLabel8.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Date"));
        jPanelPeriod.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabelTo.setFont(new java.awt.Font("SansSerif", 1, 12));
        jLabelTo.setForeground(new java.awt.Color(0, 153, 153));
        jLabelTo.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("To"));
        jPanelPeriod.add(jLabelTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 20));

        jLabelStart.setFont(new java.awt.Font("SansSerif", 3, 12));
        jLabelStart.setForeground(new java.awt.Color(0, 51, 204));
        jLabelStart.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("start"));
        jPanelPeriod.add(jLabelStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, -1));

        jLabelEnd.setFont(new java.awt.Font("SansSerif", 3, 12));
        jLabelEnd.setForeground(new java.awt.Color(0, 51, 204));
        jLabelEnd.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("end"));
        jPanelPeriod.add(jLabelEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 120, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12));
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("To"));
        jPanelPeriod.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 10, 20, -1));

        jSpinnerEndHour.setFont(new java.awt.Font("Dialog", 0, 12));
        jSpinnerEndHour.setPreferredSize(new java.awt.Dimension(35, 25));
        jSpinnerEndHour.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerEndHourStateChanged(evt);
            }
        });

        jPanelPeriod.add(jSpinnerEndHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 50, -1));

        jSpinnerStartHour.setFont(new java.awt.Font("Dialog", 0, 12));
        jSpinnerStartHour.setPreferredSize(new java.awt.Dimension(35, 25));
        jSpinnerStartHour.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStartHourStateChanged(evt);
            }
        });

        jPanelPeriod.add(jSpinnerStartHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, -1));

        jXDatePickerStart.setFont(new java.awt.Font("Dialog", 0, 12));
        jXDatePickerStart.setFormats(GUIConst.DATE_FORMAT_STRING);
        jPanelPeriod.add(jXDatePickerStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jXDatePickerEnd.setFont(new java.awt.Font("Dialog", 0, 12));
        jXDatePickerEnd.setFormats(GUIConst.DATE_FORMAT_STRING);
        jPanelPeriod.add(jXDatePickerEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jCheckSelectEndTime.setFont(new java.awt.Font("SansSerif", 0, 12));
        jCheckSelectEndTime.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Specify_End_Time"));
        jCheckSelectEndTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckSelectEndTime.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jCheckSelectEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckSelectEndTimeActionPerformed(evt);
            }
        });

        jPanelPeriod.add(jCheckSelectEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        getContentPane().add(jPanelPeriod, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Select_Time_Period"));
        jLabel1.setPreferredSize(new java.awt.Dimension(107, 50));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 70));
        jButtonOK.setFont(new java.awt.Font("SansSerif", 0, 12));
        jButtonOK.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("OK"));
        jButtonOK.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("SansSerif", 0, 12));
        jButtonCancel.setText(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Cancel"));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckSelectEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckSelectEndTimeActionPerformed
        selectEndTime = jCheckSelectEndTime.isSelected();
        setEndTimeFields();
    }//GEN-LAST:event_jCheckSelectEndTimeActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        selection = SELECTION_CANCEL;
        
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        selection = SELECTION_OK;
        getSelectedTime();
        
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    // get selected start and end time. if end time is earlier than start time, then set end time to the same as 
    // start time
    private void getSelectedTime() {
        selectEndTime = jCheckSelectEndTime.isSelected();
        
        startTime.setTime( jXDatePickerStart.getDate() );
        startTime.set( Calendar.HOUR_OF_DAY, numModelStartHour.getNumber().intValue() );
        startTime.set( Calendar.MINUTE, 0 );
        startTime.set( Calendar.SECOND, 0 );
//        startTime.set( Calendar.MINUTE, numModelStartMinute.getNumber().intValue() );
//        startTime.set( Calendar.SECOND, numModelStartSecond.getNumber().intValue() );
        
        endTime.setTime( jXDatePickerEnd.getDate() );
        endTime.set( Calendar.HOUR_OF_DAY, numModelEndHour.getNumber().intValue() );
        endTime.set( Calendar.MINUTE, 0 );
        endTime.set( Calendar.SECOND, 0 );

        if ( endTime.before( startTime )) 
            endTime.setTime( startTime.getTime() );
    
    }
    
    private void jSpinnerStartHourStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStartHourStateChanged
        
    }//GEN-LAST:event_jSpinnerStartHourStateChanged

    private void jSpinnerEndHourStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerEndHourStateChanged
        
    }//GEN-LAST:event_jSpinnerEndHourStateChanged

    private void jXDatePickerStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerStartActionPerformed
        //if ( !verifySelectedStartTime() ) {
        Date d = jXDatePickerStart.getDate();
        if ( d.before( initStartDate.getTime() ))
            jXDatePickerStart.setDate( initStartDate.getTime() );
        if ( d.after( initEndDate.getTime() ))
            jXDatePickerStart.setDate( initEndDate.getTime() );
    }//GEN-LAST:event_jXDatePickerStartActionPerformed

    private void jXDatePickerEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerEndActionPerformed
        Date d = jXDatePickerEnd.getDate();
        if ( d.before( initStartDate.getTime() ))
            jXDatePickerEnd.setDate( initStartDate.getTime() );
        if ( d.after( initEndDate.getTime() ))
            jXDatePickerEnd.setDate( initEndDate.getTime() );
    }//GEN-LAST:event_jXDatePickerEndActionPerformed
    
    public Calendar getStartTime() {
        return startTime;
    }
    
    public Calendar getEndTime() {
        return endTime;
    }
    
    public int getSelection() {
        return selection;
    }
    
    public boolean selectEndTime() {
        return selectEndTime;
    }
    
    private final int WIDTH = 600;
    private final int HEIGHT = 350;
    
    public static final int SELECTION_CANCEL = 0;
    public static final int SELECTION_OK = 1;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckSelectEndTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelEndTimeDate;
    private javax.swing.JLabel jLabelEndTimeHour;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPeriod;
    private javax.swing.JSpinner jSpinnerEndHour;
    private javax.swing.JSpinner jSpinnerStartHour;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerEnd;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerStart;
    // End of variables declaration//GEN-END:variables
    
    private Calendar startTime;
    private Calendar endTime;
    private Calendar initStartDate;  // this is to remember the initial time so that we can limit the user's choice range
    private Calendar initEndDate;
    
    private SpinnerNumberModel numModelStartHour;
    private SpinnerNumberModel numModelEndHour;
    private SpinnerNumberModel numModelStartMinute;
    private SpinnerNumberModel numModelEndMinute;
    private SpinnerNumberModel numModelStartSecond;
    private SpinnerNumberModel numModelEndSecond;
    
    
    private int selection = SELECTION_CANCEL;
    private boolean selectEndTime = false;
}
