/*
 * CalculateSettingDialog.java
 *
 * Created on 2007年4月12日, 下午11:24
 */

package com.cs.canalyzer.gui.dialog.settings;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.BasicSetting;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author  msu
 */
public class ServiceCompanySettingDialog extends javax.swing.JDialog {
    
    /** Creates new form CalculateSettingDialog */
    public ServiceCompanySettingDialog( BasicSetting basicSetting ) {
        this.myBasicSetting = basicSetting;
        
        myInit();
    }
    
    private void myInit() {
        initComponents();

        if ( myBasicSetting.ServiceCompanyName.length() > 0 )
            jTextName.setText( myBasicSetting.ServiceCompanyName );
        //public String LogoFilePath = "";
    
        jTextAddressLine1.setText( myBasicSetting.ServiceAddressLine1 );
        jTextAddressLine2.setText( myBasicSetting.ServiceAddressLine2 );
        jTextAddressLine3.setText( myBasicSetting.ServiceAddressLine3 );
        jTextResponsiblePerson.setText( myBasicSetting.ServiceResponsiblePerson );
        jTextPhone.setText( myBasicSetting.ServicePhone );
        jTextFax.setText( myBasicSetting.ServiceFax );
        jTextEmail.setText( myBasicSetting.ServiceEmail );
        jTextWebpage.setText( myBasicSetting.ServiceWebpage );
        
        //jLabelLogo.setIcon( new javax.swing.ImageIcon( myBasicSetting.ServiceLogoFilePath ));
        
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );         
        setBounds( START_X, START_Y, WIDTH, HEIGHT );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAverage = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        jButtonSelectLogo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextAddressLine1 = new javax.swing.JTextField();
        jTextAddressLine2 = new javax.swing.JTextField();
        jTextAddressLine3 = new javax.swing.JTextField();
        jTextPhone = new javax.swing.JTextField();
        jTextFax = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextWebpage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextResponsiblePerson = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Service_Company_Information")); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Service_Company_Information")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(133, 40));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12));
        jLabel2.setText(bundle.getString("Company_Name")); // NOI18N

        jTextName.setFont(DIALOG_FONT);

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonSelectLogo.setFont(new java.awt.Font("SansSerif", 0, 10));
        jButtonSelectLogo.setText(bundle.getString("Select_Logo_File")); // NOI18N
        jButtonSelectLogo.setToolTipText(bundle.getString("Click_to_select_an_image_file_as_the_company_logo._The_logo_will_appear_in_printed_reports_with_company_information.")); // NOI18N
        jButtonSelectLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectLogoActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Company_Information"))); // NOI18N

        jLabel4.setFont(DIALOG_FONT);
        jLabel4.setText(bundle.getString("Address:")); // NOI18N

        jTextAddressLine1.setFont(DIALOG_FONT);

        jTextAddressLine2.setFont(DIALOG_FONT);

        jTextAddressLine3.setFont(DIALOG_FONT);

        jTextPhone.setFont(DIALOG_FONT);

        jTextFax.setFont(DIALOG_FONT);

        jTextEmail.setFont(DIALOG_FONT);

        jTextWebpage.setFont(DIALOG_FONT);

        jLabel5.setFont(DIALOG_FONT);
        jLabel5.setText(bundle.getString("Phone:")); // NOI18N

        jLabel6.setFont(DIALOG_FONT);
        jLabel6.setText(bundle.getString("Fax:")); // NOI18N

        jLabel7.setFont(DIALOG_FONT);
        jLabel7.setText(bundle.getString("Email:")); // NOI18N

        jLabel8.setFont(DIALOG_FONT);
        jLabel8.setText(bundle.getString("Webpage:")); // NOI18N

        jLabel9.setFont(DIALOG_FONT);
        jLabel9.setText(bundle.getString("Responsible_Person:")); // NOI18N

        jTextResponsiblePerson.setFont(DIALOG_FONT);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jLabel7)
                    .add(jLabel8)
                    .add(jLabel4)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 6, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextAddressLine1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextAddressLine2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .add(jTextAddressLine3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .add(jTextResponsiblePerson, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .add(jTextPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .add(jTextFax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .add(jTextEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .add(jTextWebpage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(new java.awt.Component[] {jTextAddressLine1, jTextAddressLine2, jTextAddressLine3, jTextEmail, jTextFax, jTextPhone, jTextResponsiblePerson, jTextWebpage}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextAddressLine1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextAddressLine2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextAddressLine3)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextResponsiblePerson)
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jTextPhone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .add(18, 18, 18)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .add(20, 20, 20)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .add(18, 18, 18)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextWebpage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(20, 20, 20))
        );

        org.jdesktop.layout.GroupLayout jPanelMainLayout = new org.jdesktop.layout.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMainLayout.createSequentialGroup()
                .add(jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelMainLayout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelMainLayout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jTextName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 403, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(44, 44, 44)
                .add(jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButtonSelectLogo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabelLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMainLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelMainLayout.createSequentialGroup()
                        .add(jLabelLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonSelectLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelMainLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(50, 50, 50)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));

        jButtonOK.setFont(DIALOG_FONT);
        jButtonOK.setText(bundle.getString("OK")); // NOI18N
        jButtonOK.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(DIALOG_FONT);
        jButtonCancel.setText(bundle.getString("Cancel")); // NOI18N
        jButtonCancel.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectLogoActionPerformed
        final JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "JPG & GIF Images", "jpg", "gif","bmp","png");
        fc.setFileFilter(filter);
        if ( fc.showDialog( this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Load") ) != JFileChooser.APPROVE_OPTION ) {
            return;
        }        
        long size = fc.getSelectedFile().length();
        if(size>200*1024){
            JOptionPane.showMessageDialog(this,
                        java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Logo file size should not exceed 200 KByte")
                    );
            return;
        }
        myBasicSetting.ServiceLogoFilePath = fc.getSelectedFile().getAbsolutePath();
        repaint();
        //drawServiceLogo(myBasicSetting.ServiceLogoFilePath);
        //jLabelLogo.setIcon( new javax.swing.ImageIcon( myBasicSetting.ServiceLogoFilePath ));
    }//GEN-LAST:event_jButtonSelectLogoActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        try {
            myBasicSetting.ServiceCompanyName = jTextName.getText();
            
            myBasicSetting.ServiceAddressLine1 = jTextAddressLine1.getText();
            myBasicSetting.ServiceAddressLine2 = jTextAddressLine2.getText();
            myBasicSetting.ServiceAddressLine3 = jTextAddressLine3.getText();
            myBasicSetting.ServiceResponsiblePerson = jTextResponsiblePerson.getText();
            myBasicSetting.ServicePhone = jTextPhone.getText();
            myBasicSetting.ServiceFax = jTextFax.getText();
            myBasicSetting.ServiceEmail = jTextEmail.getText();
            myBasicSetting.ServiceWebpage = jTextWebpage.getText();
            //System.out.println(java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("ServiceCompanySettingDialog/myBasicSetting.ServiceWebpage_==_")+myBasicSetting.ServiceWebpage);

        } catch ( Exception e ) {}
        
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    public void paint( Graphics g ) {
        super.paint( g );
        
        drawServiceLogo( myBasicSetting.ServiceLogoFilePath );
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateSettingDialog().setVisible(true);
            }
        });
    }*/
    
    private final int START_X = 240;
    private final int START_Y = 120;
    private final int WIDTH = 660;
    private final int HEIGHT = 620;
    
    private final Font DIALOG_FONT = new Font( "SansSerif", 1, 10 );
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAverage;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonSelectLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextAddressLine1;
    private javax.swing.JTextField jTextAddressLine2;
    private javax.swing.JTextField jTextAddressLine3;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFax;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhone;
    private javax.swing.JTextField jTextResponsiblePerson;
    private javax.swing.JTextField jTextWebpage;
    // End of variables declaration//GEN-END:variables
    
    private BasicSetting myBasicSetting;
    
     //add by be, 2009/01/20 .
    private void drawServiceLogo(String logoPath){  
       if(logoPath != null){
         //  System.out.println("drawServiceLogo logopath = "+logoPath);
           ImageIcon serviceLogoImage = new javax.swing.ImageIcon( logoPath );
           //serviceLogoImage = PrintManager.validateAndCreateImageIcon(logoPath);
           if (serviceLogoImage != null) {              
               Graphics2D g2d = (Graphics2D) jPanelMain.getGraphics();
               int logolableWidth = jLabelLogo.getWidth();
               // Note: logoHeight is 0 by default
               int logolableHeight = jLabelLogo.getHeight();
//System.out.println( "drawing " + jLabelLogo.getX() + " " + jLabelLogo.getY() + " " + logolableWidth + " " + logolableHeight + " " );
               g2d.drawImage(serviceLogoImage.getImage(), jLabelLogo.getX(), jLabelLogo.getY(), logolableWidth, logolableHeight, null);  
           }                               
       }
      
   }
    
}
