/*
 * VFSettingDialog.java
 *
 * Created on 2009年1月29日, 下午12:40
 */

package com.cs.canalyzer.gui.dialog.settings;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.Compressor;
import com.cs.canalyzer.structs.VFConst;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Variable frequency compressor settings.
 * @author  msu
 */
public class VFSettingDialog extends javax.swing.JDialog {

    /** Creates new form VFSettingDialog */
    public VFSettingDialog( Compressor compressor ) {
        this.myCompressor = compressor;
        
        myInit();
    }

    private void myInit() {
        atInit = true;
        
        initComponents();

        initComboFields();
        jComboMotorPower.setSelectedIndex( VFConst.indexOfMotorPowerValue( myCompressor.VFMotorPower ));
        jComboSystemPressure.setSelectedIndex( VFConst.indexOfSystemPressure( myCompressor.VFSystemPressure ));
        
        setPowerAndAirFieldsBasedOnCompressor();
     
        setModalityType( ModalityType.APPLICATION_MODAL );
        setIconImage( new ImageIcon( getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );         
        setBounds( START_X, START_Y, WIDTH, HEIGHT );

        atInit = false;
    }
    
    private void initComboFields() {
        jComboMotorPower.removeAllItems();
        for ( int i = 0; i < VFConst.MOTOR_POWER_LIST.length; i++ ) {
            jComboMotorPower.addItem( VFConst.MOTOR_POWER_LIST[i] );
        }
        jComboSystemPressure.removeAllItems();
        for ( int i = 0; i < VFConst.SYSTEM_PRESSURE_LIST.length; i++ ) {
            jComboSystemPressure.addItem( VFConst.SYSTEM_PRESSURE_LIST[i] );
        }
    }
    
    private void setPowerAndAirFieldsBasedOnCompressor() {
        jTextPowerMin.setText( String.format( FORMAT_STRING_2_DIGIT , myCompressor.VFPowerMin ).trim() );
        jTextPowerP2.setText( String.format( FORMAT_STRING_2_DIGIT , myCompressor.VFPowerP2 ).trim() );
        jTextPowerP3.setText( String.format( FORMAT_STRING_2_DIGIT , myCompressor.VFPowerP3 ).trim() );
        jTextPowerMax.setText( String.format( FORMAT_STRING_2_DIGIT , myCompressor.VFPowerMax ).trim() );
        jTextAirMin.setText( String.format( FORMAT_STRING_1_DIGIT , myCompressor.VFAirDeliveryMin ).trim() );
        jTextAirP2.setText( String.format( FORMAT_STRING_1_DIGIT , myCompressor.VFAirDeliveryP2 ).trim() );
        jTextAirP3.setText( String.format( FORMAT_STRING_1_DIGIT , myCompressor.VFAirDeliveryP3 ).trim() );
        jTextAirMax.setText( String.format( FORMAT_STRING_1_DIGIT , myCompressor.VFAirDeliveryMax ).trim() );
    }
    
    private void setPowerAndAirFieldsBasedOnMotorPowerAndSystemPressure() {
        int motorPowerIndex = jComboMotorPower.getSelectedIndex();
        int pressureIndex = jComboSystemPressure.getSelectedIndex();
        jTextPowerMin.setText( String.format( FORMAT_STRING_2_DIGIT , 
                VFConst.POWER_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_MIN] ).trim() );
        jTextPowerP2.setText( String.format( FORMAT_STRING_2_DIGIT , 
                VFConst.POWER_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_P2] ).trim() );
        jTextPowerP3.setText( String.format( FORMAT_STRING_2_DIGIT , 
                VFConst.POWER_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_P3] ).trim() );
        jTextPowerMax.setText( String.format( FORMAT_STRING_2_DIGIT , 
                VFConst.POWER_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_MAX] ).trim() );
        jTextAirMin.setText( String.format( FORMAT_STRING_1_DIGIT , 
                VFConst.AIR_DELIVERY_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_MIN] ).trim() );
        jTextAirP2.setText( String.format( FORMAT_STRING_1_DIGIT , 
                VFConst.AIR_DELIVERY_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_P2] ).trim() );
        jTextAirP3.setText( String.format( FORMAT_STRING_1_DIGIT , 
                VFConst.AIR_DELIVERY_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_P3] ).trim() );
        jTextAirMax.setText( String.format( FORMAT_STRING_1_DIGIT , 
                VFConst.AIR_DELIVERY_LIST[pressureIndex][motorPowerIndex][VFConst.INDEX_MAX] ).trim() );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboMotorPower = new javax.swing.JComboBox();
        jComboSystemPressure = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextPowerMin = new javax.swing.JTextField();
        jTextPowerP2 = new javax.swing.JTextField();
        jTextPowerP3 = new javax.swing.JTextField();
        jTextPowerMax = new javax.swing.JTextField();
        jTextAirMin = new javax.swing.JTextField();
        jTextAirP2 = new javax.swing.JTextField();
        jTextAirP3 = new javax.swing.JTextField();
        jTextAirMax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonSetDefault = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("VF_Screw_Compressor")); // NOI18N
        setResizable(false);

        jLabel1.setFont(GUIConst.DIALOG_FONT);
        jLabel1.setText(bundle.getString("System_pressure:")); // NOI18N

        jLabel2.setFont(GUIConst.DIALOG_FONT);
        jLabel2.setText(bundle.getString("Motor_power:")); // NOI18N

        jComboMotorPower.setFont(GUIConst.DIALOG_FONT);
        jComboMotorPower.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboMotorPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMotorPowerActionPerformed(evt);
            }
        });

        jComboSystemPressure.setFont(GUIConst.DIALOG_FONT);
        jComboSystemPressure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboSystemPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSystemPressureActionPerformed(evt);
            }
        });

        jLabel3.setFont(GUIConst.DIALOG_FONT);
        jLabel3.setText(bundle.getString("Pa")); // NOI18N

        jLabel4.setFont(GUIConst.DIALOG_FONT);
        jLabel4.setText(bundle.getString("Power_(kW):")); // NOI18N

        jLabel5.setFont(GUIConst.DIALOG_FONT);
        jLabel5.setText(bundle.getString("Air_delivery_(m3/min):")); // NOI18N

        jTextPowerMin.setFont(GUIConst.DIALOG_FONT);
        jTextPowerMin.setPreferredSize(new java.awt.Dimension(50, 21));

        jTextPowerP2.setFont(GUIConst.DIALOG_FONT);
        jTextPowerP2.setPreferredSize(new java.awt.Dimension(50, 21));

        jTextPowerP3.setFont(GUIConst.DIALOG_FONT);
        jTextPowerP3.setPreferredSize(new java.awt.Dimension(50, 21));

        jTextPowerMax.setFont(GUIConst.DIALOG_FONT);
        jTextPowerMax.setPreferredSize(new java.awt.Dimension(50, 21));

        jTextAirMin.setFont(GUIConst.DIALOG_FONT);
        jTextAirMin.setPreferredSize(new java.awt.Dimension(50, 21));

        jTextAirP2.setFont(GUIConst.DIALOG_FONT);
        jTextAirP2.setPreferredSize(new java.awt.Dimension(50, 21));

        jTextAirP3.setFont(GUIConst.DIALOG_FONT);
        jTextAirP3.setPreferredSize(new java.awt.Dimension(50, 21));

        jTextAirMax.setFont(GUIConst.DIALOG_FONT);
        jTextAirMax.setPreferredSize(new java.awt.Dimension(50, 21));

        jLabel6.setFont(GUIConst.DIALOG_FONT);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(bundle.getString("Min")); // NOI18N

        jLabel7.setFont(GUIConst.DIALOG_FONT);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("P2");

        jLabel8.setFont(GUIConst.DIALOG_FONT);
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("P3");

        jLabel9.setFont(GUIConst.DIALOG_FONT);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(bundle.getString("Max")); // NOI18N

        jButtonSetDefault.setFont(GUIConst.DIALOG_FONT);
        jButtonSetDefault.setText(bundle.getString("Set_Default")); // NOI18N
        jButtonSetDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetDefaultActionPerformed(evt);
            }
        });

        jButtonOK.setFont(GUIConst.DIALOG_FONT);
        jButtonOK.setText(bundle.getString("OK")); // NOI18N
        jButtonOK.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(GUIConst.DIALOG_FONT);
        jButtonCancel.setText(bundle.getString("Cancel")); // NOI18N
        jButtonCancel.setPreferredSize(new java.awt.Dimension(80, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboMotorPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(jComboSystemPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextPowerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPowerP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPowerP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPowerMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextAirMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextAirP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextAirP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextAirMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSetDefault)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboMotorPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboSystemPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextPowerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPowerP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPowerP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPowerMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAirMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAirP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAirP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAirMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButtonSetDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonSetDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetDefaultActionPerformed
    setPowerAndAirFieldsBasedOnMotorPowerAndSystemPressure();
}//GEN-LAST:event_jButtonSetDefaultActionPerformed

private void jComboMotorPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMotorPowerActionPerformed
    if ( atInit ) return;
    
    setPowerAndAirFieldsBasedOnMotorPowerAndSystemPressure();
}//GEN-LAST:event_jComboMotorPowerActionPerformed

private void jComboSystemPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSystemPressureActionPerformed
    if ( atInit ) return;
    
    setPowerAndAirFieldsBasedOnMotorPowerAndSystemPressure();
}//GEN-LAST:event_jComboSystemPressureActionPerformed

private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
    if ( !verifyInput() ) {
        JOptionPane.showMessageDialog( this, ERROR_INPUT_MESSAGE );
        return;
    }
    
    myCompressor.VFMotorPower = VFConst.MOTOR_POWER_LIST[jComboMotorPower.getSelectedIndex()];
    myCompressor.VFSystemPressure = VFConst.SYSTEM_PRESSURE_LIST[jComboSystemPressure.getSelectedIndex()];
    myCompressor.VFPowerMin = powerMin;
    myCompressor.VFPowerP2 = powerP2;
    myCompressor.VFPowerP3 = powerP3;
    myCompressor.VFPowerMax = powerMax;
    myCompressor.VFAirDeliveryMin = airDeliveryMin;
    myCompressor.VFAirDeliveryP2 = airDeliveryP2;
    myCompressor.VFAirDeliveryP3 = airDeliveryP3;
    myCompressor.VFAirDeliveryMax = airDeliveryMax;
    
    if(myCompressor.hasPowerChannel()){
        myCompressor.calculateVFLinearCoefficiency();
    }else{
        myCompressor.calculateVFAmpAndLinearCoefficiency();
    }
    myCompressor.VFParameterSet = true;
    
    dispose();
}//GEN-LAST:event_jButtonOKActionPerformed

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

    private boolean verifyInput() {
        try {
            powerMin = Double.valueOf( GUIConst.VerifyString( jTextPowerMin.getText() ));
            powerP2 = Double.valueOf( GUIConst.VerifyString( jTextPowerP2.getText() ));
            powerP3 = Double.valueOf( GUIConst.VerifyString( jTextPowerP3.getText() ));
            powerMax = Double.valueOf( GUIConst.VerifyString( jTextPowerMax.getText() ));
            
            airDeliveryMin = Double.valueOf( GUIConst.VerifyString( jTextAirMin.getText() ));
            airDeliveryP2 = Double.valueOf( GUIConst.VerifyString( jTextAirP2.getText() ));
            airDeliveryP3 = Double.valueOf( GUIConst.VerifyString( jTextAirP3.getText() ));
            airDeliveryMax = Double.valueOf( GUIConst.VerifyString( jTextAirMax.getText() ));
            
            if ( powerMin > 0 && powerP2 > 0 && powerP3 > 0 && powerMax > 0
                && powerP2 > powerMin && powerP3 > powerP2 && powerMax > powerP3 
                && airDeliveryMin > 0 && airDeliveryP2 > 0 && airDeliveryP3 > 0 && airDeliveryMax > 0 
                && airDeliveryP2 > airDeliveryMin && airDeliveryP3 > airDeliveryP2 && airDeliveryMax > airDeliveryP3 ) {
                return true;
            } else
                return false;
        } catch( Exception e ) {
            return false;
        }
    }

    private final int START_X = 130;
    private final int START_Y = 80;
    private final int WIDTH = 530;
    private final int HEIGHT = 300;

    private final String FORMAT_STRING_1_DIGIT = "%10.1f";
    private final String FORMAT_STRING_2_DIGIT = "%10.2f";

    private final String ERROR_INPUT_MESSAGE = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<html>Input_values_are_not_valid._Please_note:") +
            java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<br><br>1_All_fields_have_to_be_entered;") +
            java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<br>2_All_fields_must_have_non-negative_value;") +
            java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("<br>3_Power_and_air_delivery_values_must_be_in_increasing_order.") +
            "<br><br><br></html>";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonSetDefault;
    private javax.swing.JComboBox jComboMotorPower;
    private javax.swing.JComboBox jComboSystemPressure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextAirMax;
    private javax.swing.JTextField jTextAirMin;
    private javax.swing.JTextField jTextAirP2;
    private javax.swing.JTextField jTextAirP3;
    private javax.swing.JTextField jTextPowerMax;
    private javax.swing.JTextField jTextPowerMin;
    private javax.swing.JTextField jTextPowerP2;
    private javax.swing.JTextField jTextPowerP3;
    // End of variables declaration//GEN-END:variables

    private Compressor myCompressor;
    
    private double powerMin, powerP2, powerP3, powerMax;
    private double airDeliveryMin, airDeliveryP2, airDeliveryP3, airDeliveryMax;
    
    private boolean atInit = false;  // when initialization don't trigger events

}
