/*
 * ShuttingDown.java
 *
 * Created on 2006年2月16日, 下午5:45
 */

package com.cs.canalyzer.file.export;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.canalyzer.structs.CommonValue;
import com.cs.database.*;
import com.cs.license.LicenseConst;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.*;
import java.nio.channels.FileChannel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.*;
import jxl.SheetSettings;
import jxl.Workbook;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.*;

/**
 *
 * @author  msu
 */
public class ExportingDataDialog extends javax.swing.JFrame {

    /** Creates new form ShuttingDown */
    public ExportingDataDialog( final CSMDF db, long pref, String fileName ) {
        myThread = new ExportDataInBackground( db, pref, fileName, this );

        myInit();
    }
    
    /** if the user choose to shrink the data. */
    public ExportingDataDialog( final CSMDF db, long pref, String fileName, boolean shrinkData ) {
        myThread = new ExportDataInBackground( db, pref, fileName, this );
        this.shrinkData = shrinkData;

        myInit();
    }

    //save in different excel files. ------------ begin
    private boolean isBigFile = false;
    public ExportingDataDialog( final CSMDF db, long pref, String fileName, boolean shrinkData, boolean isBig ) {
        myThread = new ExportDataInBackground( db, pref, fileName, this );
        this.shrinkData = shrinkData;
        isBigFile = isBig;
        myInit();
    }
    //------------ end

    /** export within a certain range */
    public ExportingDataDialog( final CSMDF db, long pref, String fileName, int startID, int endID ) {
        myThread = new ExportDataInBackground( db, pref, fileName, this );
        this.startID = startID;
        this.endID = endID;
        isBigFile = true;//add by be on 20100917.
        System.out.println("ExportingData/startID="+startID);
        System.out.println("ExportingData/endID="+endID);
        myInit();
    }
    
    
     /**
     * Added on 20121010. Be
     * Export to CSV file.
     * fileMode : 1 : excel file; 2 : CSV file.
     */
    public ExportingDataDialog( final CSMDF db, long pref, String fileName, int fileMode ) {
        myThread = new ExportDataInBackground( db, pref, fileName, this );
        this.exportFileTpye = fileMode;
        myInit();
    }
    
     /**
     * Added on 20131216. Be
     * Export to CSV file base on time period.
     * fileMode : 1 : excel file; 2 : CSV file.
     */
    public ExportingDataDialog( final CSMDF db, long pref, String fileName, int fileMode, int startID, int endID ) {
        myThread = new ExportDataInBackground( db, pref, fileName, this );
        this.exportFileTpye = fileMode;
        this.startID = startID;
        this.endID = endID;
        myInit();
    }

    private void myInit() {
        initComponents();
   
        jProgressBarMain.setMaximum( MAX_PROGRESS_VALUE );
        jProgressBarMain.setMinimum( MIN_PROGRESS_VALUE );
        jProgressBarMain.setValue( MIN_PROGRESS_VALUE );
        
        //this.setIconImage( new ImageIcon(getClass().getResource( "/com/cs/gui/img/" + GUIConst.LOGO_FILE_NAME)).getImage() );
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );
   
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( (dim.width - WIDTH) / 2, (dim.height - HEIGHT) / 2, WIDTH, HEIGHT);
        
        initTimer();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBarMain = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Message")); // NOI18N
        setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        setResizable(false);

        jPanel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("Exporting_data_This_may_take_a_while")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jProgressBarMain.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel1.add(jProgressBarMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(20, 10));
        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 10));
        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(10, 20));
        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void initTimer() {
        Action refreshAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                if (isShowing()) {
                    if (!myThread.isAlive()) {
                        myThread.setPriority( Thread.NORM_PRIORITY - 2);
                        myThread.start();
                    } 

                    oneStepForward();
                }
            }
        };
        
        //if (timer != null) timer.stop();
        timer = new Timer(300, refreshAction);
        //timer.setDelay(500);
        timer.start();
    }    
    
    public void stopTimer() {
        timer.stop();
    }
    
    public void oneStepForward() {
        int value = jProgressBarMain.getValue();
        value += STEP;
        if (value > MAX_PROGRESS_VALUE) value = MIN_PROGRESS_VALUE;
        jProgressBarMain.setValue(value);
    }
    
    
 
private class ExportDataInBackground extends Thread {
    public ExportDataInBackground( final CSMDF db, long pref, String fileName, final ExportingDataDialog parentDlg ) {
//        this.myDB = db;
        this.pref = pref;
        this.fileName = fileName;
        this.parentDlg = parentDlg;
    }
    
    public void run() {
        
        int result;
        int reply;
         
         //csv and excel
        if(exportFileTpye == EXPORT_CSV_FILE){
             result = exportPHeaderToCSV( pref, fileName, parentDlg.startID, parentDlg.endID, parentDlg.shrinkData, false );
            if ( result == DBMessage.CSDB_FILE_ALREADY_EXIST ) {
                reply = JOptionPane.showConfirmDialog( parentDlg, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Target_file_already_exists"),
                        java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Please_Confirm"),
                        JOptionPane.YES_NO_OPTION );
                if ( reply != JOptionPane.YES_OPTION ) {
                    parentDlg.dispose();
                    return;
                } else
                    result = exportPHeaderToCSV( pref, fileName, parentDlg.startID, parentDlg.endID, parentDlg.shrinkData, true );
            }
        }else{
         
         
            result = exportBigPHeaderToExcel( pref, fileName, parentDlg.startID, parentDlg.endID, parentDlg.shrinkData, false );

            if ( result == DBMessage.CSDB_FILE_ALREADY_EXIST ) {
                reply = JOptionPane.showConfirmDialog( parentDlg, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Target_file_already_exists"), 
                        java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Please_confirm"),
                        JOptionPane.YES_NO_OPTION );
                if ( reply != JOptionPane.YES_OPTION ) {
                    parentDlg.dispose();
                    return;
                } else 
                    result = exportBigPHeaderToExcel( pref, fileName, parentDlg.startID, parentDlg.endID, parentDlg.shrinkData, true );
            }
        }
        
        parentDlg.stopTimer();
        if ( result == DBMessage.CSDB_OK ) {

            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Data_exported"));
        } else if ( result == DBMessage.CSDB_FILE_CURRENTLY_OPENED ) {
            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("File_in_use_export_fail"));
        } else {
            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Sorry_Exportation_failed"));
        }
        parentDlg.dispose();
      
    }
    
//    private CSMDF myDB;
    private long pref;
    private String fileName;
    private ExportingDataDialog parentDlg;
}    
    
    
    private static final int WIDTH = 400;
    private static final int HEIGHT = 100;
    
    private static final int MAX_PROGRESS_VALUE = 100;
    private static final int MIN_PROGRESS_VALUE = 0;
    private static final int STEP = 2;
    
    private static String shortDateFormatStyle = null;
    static{
        shortDateFormatStyle = DataFormatStyleUtil.getLocalShortDateFormatString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBarMain;
    // End of variables declaration//GEN-END:variables
    
    private ExportDataInBackground myThread;
    private Timer timer;
    
    public boolean shrinkData = false;
    public int startID = -1; // to define range. less than 0 means don't use it
    public int endID = -1; // same with 'startID'
    
    //added by be on 20121010, Richard's requirement, export to csv file. ---------- begin
    private int exportFileTpye = EXPORT_EXCEL_FILE; //1 : excel; 2 : csv
    public static int EXPORT_EXCEL_FILE = 1;
    public static int EXPORT_CSV_FILE = 2;
    
    private final static String EXPORT_FILE_VERSION = "V1";
    // -------------- end
    public int exportPHeaderToCSV(long pref, String excelFileName, int startID, int endID, boolean shrinkData, boolean replaceExistingFile) {
       
        try {
            // ################ check if record file exists, target file exist #######################
            File file = CSMDF.findRecordFile( pref );
            if ( file == null ) return DBMessage.CSDB_FILE_DOES_NOT_EXIST;

            if ( !excelFileName.endsWith( ".csv") && !excelFileName.endsWith( ".CSV") )
                excelFileName += ".csv";

            File targetFile = new File( excelFileName );
            if ( targetFile.exists() ) {
                if ( !replaceExistingFile )
                    return DBMessage.CSDB_FILE_ALREADY_EXIST;
                else {
                    if ( !targetFile.delete() )
                        return DBMessage.CSDB_FILE_CURRENTLY_OPENED;
                }
            }

            NProtocolHeader pheader = new NProtocolHeader();
            int row = 0;
            String name;       
            long stime;
            ArrayList<NChannelHeader> chheaders = new ArrayList<NChannelHeader>();
            int chSize;
            NChannelHeader chheader;
            jxl.write.Number number;
            long timeDiffPerID;
            long recordStartPosition;
            int recordID;
            int startRecordNo, endRecordNo;
            int lengthPerLine;


            // ######################  read record file information ###############################

            RandomAccessFile ranFileRead = new RandomAccessFile ( file, CSMDF.RANDOM_READ_FILE_ACCESS_MODE );            
            pheader.readFromFile( ranFileRead,  CSMDF.POSITION_PROTOCOL_HEADER );
            stime = pheader.StartTime;
            pheader.StopTime = CSMDF.calculateEndTime(pheader.Pref);
            timeDiffPerID = pheader.SampleRate * pheader.SampleRateFactor;
            lengthPerLine = NMeasurementRecord.ID_LENGTH + pheader.NumOfChannels * NMeasurementRecord.VALUE_LENGTH;

//            for ( int i = 0; i < pheader.NumOfChannels; i++ ) {
//                NChannelHeader ch = new NChannelHeader();
//                ch.readFromFile( ranFileRead, ranFileRead.getFilePointer() );
//                chheaders.add( ch );
//            }
//            chSize = chheaders.size();
//            if ( chSize == 0) {
//                // nothing found
//                ranFileRead.close();
//                return DBMessage.CSDB_NO_DATA_AVAILABLE;
//            }

            ranFileRead.seek( CSMDF.POSITION_RECORD_POSITION_POINTER );
            recordStartPosition= ranFileRead.readLong();

            for ( long position = CSMDF.POSITION_1ST_CHANNEL_HEADER; position < recordStartPosition; 
                                        position += NChannelHeader.LENGTH ) {
                NChannelHeader ch = new NChannelHeader();
                ch.readFromFile( ranFileRead, position );
                chheaders.add( ch );
            }
            chSize = chheaders.size();
            if ( chSize == 0) {
                // nothing found
                ranFileRead.close();
                return DBMessage.CSDB_NO_DATA_AVAILABLE;
            }
            
            // find out start and end record number
            if (startID >= 0 && endID >= 0) {
                //mrecords = queryMeasurementRecordWithinCertainPeriod( chheaders.get(i).cref, startID, endID );
                startRecordNo = startID; endRecordNo = endID;
//                ranFileRead.seek(recordStartPosition + startID * lengthPerLine);
//                recordID = ranFileRead.readInt();
//                while( recordID < startID ) {
//                    ranFileRead.seek(ranFileRead.getFilePointer() - NMeasurementRecord.ID_LENGTH - lengthPerLine);
//                    recordID = ranFileRead.readInt();
//                    startRecordNo -= 1;
//                }
//                ranFileRead.seek(recordStartPosition + endID * lengthPerLine);
//                recordID = ranFileRead.readInt();
//                while( recordID < endID ) {
//                    ranFileRead.seek(ranFileRead.getFilePointer() - NMeasurementRecord.ID_LENGTH - lengthPerLine);
//                    recordID = ranFileRead.readInt();
//                    endRecordNo -= 1;
//                }
            } else {
                //mrecords = queryMeasurementRecord(chheaders.get(i).cref);
                startRecordNo = 0;
                endRecordNo = pheader.NumOfSamples - 1;
            }

            ranFileRead.close();

            // ############ start to create excel file ################################

            FileOutputStream csvFileOut = new FileOutputStream( targetFile );            
            OutputStreamWriter csvFileOutWriter = new OutputStreamWriter(csvFileOut,"UTF-8");            
            BufferedWriter csvFileBufWriter = new BufferedWriter(csvFileOutWriter);            
            String changedOneLine = "\r\n";

            String softwareName = "";
//            if(LicenseConst.EXPORTEXCEL_SOFTWARENAME == null || "".equals(LicenseConst.EXPORTEXCEL_SOFTWARENAME)){
                softwareName = "CAA";
//            }else{
//                softwareName = LicenseConst.EXPORTEXCEL_SOFTWARENAME ;
//            }

//            DateFormat customDateFormat = new DateFormat("MM/dd/yyyy hh:mm:ss");
            SimpleDateFormat sdf= new SimpleDateFormat(shortDateFormatStyle+" HH:mm:ss");
            
            //soon
            csvFileBufWriter.write(softwareName+ "," + EXPORT_FILE_VERSION +changedOneLine);
            csvFileBufWriter.write(changedOneLine);
            csvFileBufWriter.write( "Description"+","+ pheader.getDescription()+","+ changedOneLine );
            
            csvFileBufWriter.write("Start Time" + "," +  sdf.format(pheader.StartTime) +","+ changedOneLine  );

            if ( pheader.StopTime != NProtocolHeader.DEFAULT_START_AND_END_TIME ) {
               csvFileBufWriter.write("End Time" + "," +  sdf.format( pheader.StopTime )+","+ changedOneLine  );
            }

            csvFileBufWriter.write("Sample Rate (sec)" + "," + pheader.SampleRate * pheader.SampleRateFactor / 1000+","+ changedOneLine +changedOneLine+changedOneLine );

            String tilie = "";
            tilie = "TIME";
            String tempUnit = "";
            char cubeSymbol = 0xB3;
            
            for ( int i = 0; i < chSize; i++ ) {
                chheader = chheaders.get( i );
                name = CommonValue.getViewChannelFullName(pheader, chheader);
//                name = chheader.getDescription();
//                tempUnit = chheader.getUnitText(); 
////                tempUnit = new String(tempUnit.getBytes(), "utf-8"); 
//                if(tempUnit != null){
//            
//                    tempUnit = tempUnit.replace(cubeSymbol, '3');
//                }
//                name += "(" + tempUnit + ")";
                tilie +=","+name;
            }
            csvFileBufWriter.write(tilie+changedOneLine);

            // ###########################  now data ################################
            String oneLineData = "";
            int resolution;
            int[] floatFormats = new int[chSize];
            String formatString;
            FileInputStream fileIn = new FileInputStream(file);
            FileChannel fileChannel = fileIn.getChannel();
            byte[] byteDouble = new byte[8];
            double value;
            byte[] byteInt = new byte[4];
            int id;
            int recordRow = row;

            // get formats
            for ( int i = 0; i < chSize; i++ ) {
                chheader = chheaders.get( i );
                // deal with format
                resolution  = chheader.Resolution;
                if(resolution < 0) resolution = 0;
                floatFormats[i] = resolution;
            }

            if (( startID >=0 && endID >= 0 ) || (( startID <= 0 || endID <= 0 ) && !shrinkData )) {
                oneLineData = "";
                fileChannel.position( recordStartPosition + startRecordNo * lengthPerLine );
                for ( int i = startRecordNo; i <= endRecordNo; i++ ) {
                    fileIn.read( byteInt, 0, 4 );
                    id = CSMDF.byteArrayToInt( byteInt );
                    oneLineData = sdf.format( stime + timeDiffPerID * id );
                    for ( int j = 0; j < chSize; j++ ) {
                        fileIn.read( byteDouble, 0, 8 );
                        value = CSMDF.byteArrayToDouble( byteDouble );
                        oneLineData += ","+ String.format("%." + floatFormats[j] + "f", value) ;
                    }
                    oneLineData += changedOneLine;
                    csvFileBufWriter.write(oneLineData);
                } // cycle of record lines

            } else {
            }

            fileIn.close();
            csvFileBufWriter.close();
            csvFileOutWriter.close();
            csvFileOut.close();

        } catch ( Exception e ) {          
            e.printStackTrace();
            return DBMessage.CSDB_EXPORT_FAIL;
        }

        return DBMessage.CSDB_OK;
    }
    
    public int exportBigPHeaderToExcel( long pref, String excelFileName, int startID, int endID, boolean shrinkData, boolean replaceExistingFile ) {
         try {
            // ################ check if record file exists, target file exist #######################
            File file = CSMDF.findRecordFile( pref );
            if ( file == null ) return DBMessage.CSDB_FILE_DOES_NOT_EXIST;

            if ( !excelFileName.endsWith( ".XLS") && !excelFileName.endsWith( ".xls") )
                excelFileName += ".xls";
//            System.out.println("CSMF/exportPHeaderToExcel excelFileName="+excelFileName);
            File targetFile = new File( excelFileName );
            if ( targetFile.exists() ) {
                if ( !replaceExistingFile )
                    return DBMessage.CSDB_FILE_ALREADY_EXIST;
                else {
                    if ( !targetFile.delete() )
                        return DBMessage.CSDB_FILE_CURRENTLY_OPENED;
                }
            }

            NProtocolHeader pheader = new NProtocolHeader();
            int row = 0;
            String name;
            Date time = new Date();
            long stime;
            ArrayList<NChannelHeader> chheaders = new ArrayList<NChannelHeader>();
            int chSize;
            NChannelHeader chheader;
            //ArrayList<MeasurementRecord> mrecords;
            //MeasurementRecord mrecord;
            Label label;
            jxl.write.Number number;
            DateTime dateTime;
            WritableSheet sheet;
            int page = 1;
            long timeDiffPerID;
            long recordStartPosition;
            int recordID;
            int startRecordNo, endRecordNo;
            int lengthPerLine;

            //big csd file ----------------- begin
            //solution is spilt many files and then merge them

            ArrayList tmpFileList = new ArrayList();
            //root xls file
//            System.out.println("CSMF/export to excle file root xls file targetFile="+targetFile);
            tmpFileList.add(targetFile);
            //------------- end

            // ######################  read record file information ###############################

            RandomAccessFile ranFileRead = new RandomAccessFile ( file, CSMDF.RANDOM_READ_FILE_ACCESS_MODE );
            pheader.readFromFile( ranFileRead,  CSMDF.POSITION_PROTOCOL_HEADER );
            stime = pheader.StartTime;              
            pheader.StopTime = CSMDF.calculateEndTime(pheader.Pref);//add by be on 20100915.
            timeDiffPerID = pheader.SampleRate * pheader.SampleRateFactor;
            lengthPerLine = NMeasurementRecord.ID_LENGTH + pheader.NumOfChannels * NMeasurementRecord.VALUE_LENGTH;

            

            ranFileRead.seek( CSMDF.POSITION_RECORD_POSITION_POINTER );
            recordStartPosition= ranFileRead.readLong();
            
            for ( long position = CSMDF.POSITION_1ST_CHANNEL_HEADER; position < recordStartPosition; 
                                        position += NChannelHeader.LENGTH ) {
                NChannelHeader ch = new NChannelHeader();
                ch.readFromFile( ranFileRead, position );
                chheaders.add( ch );
            }
            chSize = chheaders.size();
            if ( chSize == 0) {
                // nothing found
                ranFileRead.close();
                return DBMessage.CSDB_NO_DATA_AVAILABLE;
            }

            // find out start and end record number
            if (startID >= 0 && endID >= 0) {
                //mrecords = queryMeasurementRecordWithinCertainPeriod( chheaders.get(i).cref, startID, endID );
                startRecordNo = startID; endRecordNo = endID;
                ranFileRead.seek(recordStartPosition + startID * lengthPerLine);
                recordID = ranFileRead.readInt();
//                while( recordID < startID ) {
//                    ranFileRead.seek(ranFileRead.getFilePointer() - NMeasurementRecord.ID_LENGTH - lengthPerLine);
//                    recordID = ranFileRead.readInt();
//                    startRecordNo -= 1;
//                }
                 while( recordID < startID ) {
                    ranFileRead.seek(ranFileRead.getFilePointer() - NMeasurementRecord.ID_LENGTH + lengthPerLine);
                    recordID = ranFileRead.readInt();
                    startRecordNo += 1;
                }
                ranFileRead.seek(recordStartPosition + endID * lengthPerLine);
                recordID = ranFileRead.readInt();
//                while( recordID < endID ) {
//                    ranFileRead.seek(ranFileRead.getFilePointer() - NMeasurementRecord.ID_LENGTH - lengthPerLine);
//                    recordID = ranFileRead.readInt();
//                    endRecordNo -= 1;
//                }
                 while( recordID > endID ) {
                    ranFileRead.seek(ranFileRead.getFilePointer() - NMeasurementRecord.ID_LENGTH - lengthPerLine);
                    recordID = ranFileRead.readInt();
                    endRecordNo -= 1;
                }
            } else {
                //mrecords = queryMeasurementRecord(chheaders.get(i).cref);
                startRecordNo = 0;
                endRecordNo = pheader.NumOfSamples - 1;
            }
           
            ranFileRead.close();


            long onefilelines = 600000/chSize;

            if(64 < pheader.NumOfChannels) onefilelines = 1000;
            if((64 >= pheader.NumOfChannels) && (pheader.NumOfChannels  > 32)) onefilelines = 5000;
//            if((32 >= pheader.NumOfChannels) && (pheader.NumOfChannels  > 16)) onefilelines = 12000;
            if((32 >= pheader.NumOfChannels) && (pheader.NumOfChannels  >= 8)) onefilelines = 10000;
            if(pheader.NumOfChannels <= 7 ) onefilelines = 30000;
            if(pheader.NumOfChannels <= 4 ) onefilelines = 40000;
            if(onefilelines > 63998) onefilelines = CSMDF.MAX_EXCEL_LINES_ALLOWED;
//            System.out.println("CSMF/chSize="+chSize);
//            System.out.println("CSMF/onefilelines="+onefilelines);

            // ############ start to create excel file ################################

            WritableWorkbook workbook = Workbook.createWorkbook( targetFile );

//            DateFormat customDateFormat = new DateFormat("dd.MM.yyyy hh:mm:ss");
            DateFormat customDateFormat = new DateFormat(shortDateFormatStyle
                    + " HH:mm:ss");
            WritableCellFormat dateFormat = new WritableCellFormat( customDateFormat );
            WritableFont font = new WritableFont( WritableFont.createFont( "SansSerif" ), WritableFont.DEFAULT_POINT_SIZE + 2,
                    WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.GREEN );
            WritableCellFormat headerFormat = new WritableCellFormat( font );
            font = new WritableFont( WritableFont.createFont( "SansSerif" ), WritableFont.DEFAULT_POINT_SIZE, WritableFont.BOLD );
            WritableCellFormat titleFormat = new WritableCellFormat( font );

            //String sheetName = "" + ( ( page - 1 ) * MAX_EXCEL_LINES_ALLOWED + "~" + page * MAX_EXCEL_LINES_ALLOWED );
            String sheetName = pheader.getDescription();
            if ( sheetName.length() > CSMDF.EXCEL_SHEET_NAME_LENGTH )
                sheetName = sheetName.substring( 0, CSMDF.EXCEL_SHEET_NAME_LENGTH );
            sheet = workbook.createSheet( sheetName, page);
            SheetSettings sheetSetting = sheet.getSettings();
            sheetSetting.setDefaultColumnWidth( CSMDF.EXPORT_DEFAULT_COLUMN_WIDTH );

            // export the protocol header information
            //modify on 20090610.
            //reason : new requirement : add their software name into excel when data export to excel.
//            if(LicenseConst.EXPORTEXCEL_SOFTWARENAME == null || "".equals(LicenseConst.EXPORTEXCEL_SOFTWARENAME)){
                label = new Label( 0, row, "CAA", headerFormat );      sheet.addCell( label );
//            }else{
//                label = new Label( 0, row, LicenseConst.EXPORTEXCEL_SOFTWARENAME, headerFormat );      sheet.addCell( label );
//            }
            label = new Label( 1, row, EXPORT_FILE_VERSION, headerFormat );            sheet.addCell( label );
            row += 2;

            label = new Label( 0, row, "Description", titleFormat );            sheet.addCell( label );
            label = new Label( 1, row, pheader.getDescription() );            sheet.addCell( label );
            row++;
            label = new Label( 0, row, "Start Time", titleFormat );            sheet.addCell( label );
//            label = new Label( 1, row, DEFAULT_DATE_AND_TIME_FORMAT( pheader.StartTime ));            sheet.addCell( label );
            pheader.StartTime = pheader.StartTime/1000*1000;
            time.setTime( pheader.StartTime );
            dateTime = new DateTime( 1, row, time, dateFormat );        sheet.addCell( dateTime );
            row++;
            if ( pheader.StopTime != NProtocolHeader.DEFAULT_START_AND_END_TIME ) {
                label = new Label( 0, row, "End Time", titleFormat );                sheet.addCell( label );
//                label = new Label( 1, row, DEFAULT_DATE_AND_TIME_FORMAT( pheader.StopTime ));                sheet.addCell( label );
                pheader.StopTime = pheader.StopTime/1000*1000;
                time.setTime( pheader.StopTime );
                dateTime = new DateTime( 1, row, time, dateFormat );        sheet.addCell( dateTime );
                row++;
            }
            label = new Label( 0, row, "Sample Rate (sec)", titleFormat );            sheet.addCell( label );
            label = new Label( 1, row, pheader.SampleRate * pheader.SampleRateFactor / 1000 + "" );            sheet.addCell( label );
            //number = new jxl.write.Number( 1, row, pheader.srate );            sheet.addCell( number );
            row++;

//            //Time Period of the whole file------ begin
//                System.out.println("row="+row);
//                label = new Label( 0, row, "Time Period :", titleFormat );                sheet.addCell( label );
//                label = new Label( 1, row, DEFAULT_DATE_AND_TIME_FORMAT( pheader.StartTime ));                sheet.addCell( label );
//                label = new Label( 2, row,"To");                sheet.addCell( label );
//                label = new Label( 3, row, DEFAULT_DATE_AND_TIME_FORMAT( pheader.StartTime+pheader.SampleRate * pheader.SampleRateFactor*onefilelines ));                sheet.addCell( label );
//                //time.setTime( pheader.etime.getTime() );
//                //dateTime = new DateTime( 1, row, time, dateFormat );        sheet.addCell( dateTime );
//                row++;
//
//            //--------- end

            // now header
            row += 2;
            label = new Label( 0, row, "TIME", titleFormat );    sheet.addCell( label );
            for ( int i = 0; i < chSize; i++ ) {
                chheader = chheaders.get( i );
                name = CommonValue.getViewChannelFullName(pheader, chheader);
//                name = chheader.getDescription();
//                name += "(" + chheader.getUnitText() + ")";
                label = new Label( i + 1, row, name, titleFormat );    sheet.addCell( label );
            }

            // ###########################  now data ################################
            row++;

            int resolution;
            WritableCellFormat[] floatFormats = new WritableCellFormat[chSize];
            String formatString;
            FileInputStream fileIn = new FileInputStream(file);
            FileChannel fileChannel = fileIn.getChannel();
            byte[] byteDouble = new byte[8];
            double value;
            byte[] byteInt = new byte[4];
            int id;
            int recordRow = row;

            // get formats
            for ( int i = 0; i < chSize; i++ ) {
                chheader = chheaders.get( i );
                // deal with format
                resolution  = chheader.Resolution;
                formatString = "0";
                for ( int ii = 0; ii < resolution; ii++ ) {
                    if ( ii == 0 ) formatString += ".0";
                    else formatString += "0";
                }
                floatFormats[i] = new WritableCellFormat( new NumberFormat( formatString ) );
            }

            if (( startID >=0 && endID >= 0 ) || (( startID <= 0 || endID <= 0 ) )) {
                fileChannel.position( recordStartPosition + startRecordNo * lengthPerLine );
                int filesize = tmpFileList.size();
                int tmprowsize = 0;
                
                stime = stime/1000*1000 ;
                
                for ( int i = startRecordNo; i <= endRecordNo; i++ ) {

                    if(recordRow < onefilelines ){
                        fileIn.read( byteInt, 0, 4 );
                        id = CSMDF.byteArrayToInt( byteInt );
                        time.setTime( stime + timeDiffPerID * id );                       
                        dateTime = new DateTime( 0, recordRow, time, dateFormat );        sheet.addCell( dateTime );

                        for ( int j = 0; j < chSize; j++ ) {
                            fileIn.read( byteDouble, 0, 8 );
                            value = CSMDF.byteArrayToDouble( byteDouble );
                            number = new jxl.write.Number( j + 1, recordRow, value, floatFormats[j] );
                            sheet.addCell( number );
                        }

//               //check the period time ------begin
//               if((recordRow+1) == onefilelines){
//                    label = new Label( 3, 6, DEFAULT_DATE_AND_TIME_FORMAT( time.getTime() ));
//                    sheet.addCell( label );
//               }
//               // ----------- end
//                        System.out.println("CSMF/export before recordRow="+recordRow);

                    }else{

//                        fileIn.read( byteInt, 0, 4 );
//                        id = byteArrayToInt( byteInt );
//                        time.setTime( stime + timeDiffPerID * id );

//                           sheet = null;
                           //create other xls file
                            if(recordRow/onefilelines == filesize){
                                workbook.write();
                                workbook.close();
                                workbook = null;
                                tmprowsize = 0;
                                File tmpTargetFile = new File( excelFileName.substring(0,(excelFileName.length()-4))+"-"+filesize+".xls");
//                                if(!tmpTargetFile.exists())
//                                System.out.println("CSMF/NET xls file tmpTargetFile="+tmpTargetFile);
//                                System.out.println("CSMF/NET xls before file filesize="+filesize);
                                tmpFileList.add(tmpTargetFile);
                                filesize = tmpFileList.size();
//                                System.out.println("CSMF/NET xls file filesize="+filesize);
                                workbook = Workbook.createWorkbook( tmpTargetFile );

                                //don't meger need the title setting --begin
//                                 customDateFormat = new DateFormat("dd.MM.yyyy hh:mm:ss");
                                 customDateFormat = new DateFormat("MM/dd/yyyy hh:mm:ss");
                                 dateFormat = new WritableCellFormat( customDateFormat );
                                 font = new WritableFont( WritableFont.createFont( "SansSerif" ), WritableFont.DEFAULT_POINT_SIZE + 2,
                                        WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.GREEN );
                                 headerFormat = new WritableCellFormat( font );
                                 font = new WritableFont( WritableFont.createFont( "SansSerif" ), WritableFont.DEFAULT_POINT_SIZE, WritableFont.BOLD );
                                 titleFormat = new WritableCellFormat( font );
                                //don't meger need the title setting --end
                                sheet = workbook.createSheet( sheetName, page);
                                sheetSetting = sheet.getSettings();
                                sheetSetting.setDefaultColumnWidth( CSMDF.EXPORT_DEFAULT_COLUMN_WIDTH );

                                //test ------- begin
                                // export the protocol header information
                                //modify on 20090610.
                                //reason : new requirement : add their software name into excel when data export to excel.
//                                if(LicenseConst.EXPORTEXCEL_SOFTWARENAME == null || "".equals(LicenseConst.EXPORTEXCEL_SOFTWARENAME)){
                                    label = new Label( 0, tmprowsize, "CAA", headerFormat );      sheet.addCell( label );
//                                }else{
//                                    label = new Label( 0, tmprowsize, LicenseConst.EXPORTEXCEL_SOFTWARENAME, headerFormat );      sheet.addCell( label );
//                                }
                                label = new Label( 1, tmprowsize, EXPORT_FILE_VERSION, headerFormat );            sheet.addCell( label );
                                tmprowsize += 2;

                                label = new Label( 0, tmprowsize, "Description", titleFormat );            sheet.addCell( label );
                                label = new Label( 1, tmprowsize, pheader.getDescription() );            sheet.addCell( label );
                                tmprowsize++;
                                label = new Label( 0, tmprowsize, "Start Time", titleFormat );            sheet.addCell( label );
//                                label = new Label( 1, tmprowsize, DEFAULT_DATE_AND_TIME_FORMAT( pheader.StartTime ));            sheet.addCell( label );
                                time.setTime( pheader.StartTime );
                                dateTime = new DateTime( 1, tmprowsize, time, dateFormat );        sheet.addCell( dateTime );
                                tmprowsize++;
                                if ( pheader.StopTime != NProtocolHeader.DEFAULT_START_AND_END_TIME ) {
                                    label = new Label( 0, tmprowsize, "End Time", titleFormat );                sheet.addCell( label );
//                                    label = new Label( 1, tmprowsize, DEFAULT_DATE_AND_TIME_FORMAT( pheader.StopTime ));                sheet.addCell( label );
                                    time.setTime( pheader.StopTime );
                                    dateTime = new DateTime( 1, tmprowsize, time, dateFormat );        sheet.addCell( dateTime );
//                                    dateTime = new DateTime( 1, row, time, dateFormat );        sheet.addCell( dateTime );
                                    tmprowsize++;
                                }
                                label = new Label( 0, tmprowsize, "Sample Rate (sec)", titleFormat );            sheet.addCell( label );
                                label = new Label( 1, tmprowsize, pheader.SampleRate * pheader.SampleRateFactor / 1000 + "" );            sheet.addCell( label );
                                //number = new jxl.write.Number( 1, tmprowsize, pheader.srate );            sheet.addCell( number );
                                tmprowsize++;

//                                 //Time Period of the whole file------ begin
//
//                                    label = new Label( 0, tmprowsize, "Time Period :", titleFormat );                sheet.addCell( label );
//                                    label = new Label( 1, tmprowsize, DEFAULT_DATE_AND_TIME_FORMAT( time.getTime() ));                sheet.addCell( label );
//                                    label = new Label( 2, tmprowsize,"To");                sheet.addCell( label );
//                                    label = new Label( 3, tmprowsize, DEFAULT_DATE_AND_TIME_FORMAT( 0 ));                sheet.addCell( label );
//                                    //time.setTime( pheader.etime.getTime() );
//                                    //dateTime = new DateTime( 1, row, time, dateFormat );        sheet.addCell( dateTime );
//                                    tmprowsize++;
//
//                                //--------- end

                                // get formats
                                for ( int k = 0; k < chSize; k++ ) {
                                    chheader = chheaders.get( k );
                                    // deal with format
                                    resolution  = chheader.Resolution;
                                    formatString = "0";
                                    for ( int ii = 0; ii < resolution; ii++ ) {
                                        if ( ii == 0 ) formatString += ".0";
                                        else formatString += "0";
                                    }
                                    floatFormats[k] = new WritableCellFormat( new NumberFormat( formatString ) );
                                }

                                // now header
                                tmprowsize += 2;
                                label = new Label( 0, tmprowsize, "TIME", titleFormat );    sheet.addCell( label );
                                for ( int ii = 0; ii < chSize; ii++ ) {
                                    chheader = chheaders.get( ii );
                                    name = CommonValue.getViewChannelFullName(pheader, chheader);
//                                    name = chheader.getDescription();
//                                    name += "(" + chheader.getUnitText() + ")";
                                    label = new Label( ii + 1, tmprowsize, name, titleFormat );    sheet.addCell( label );
                                }

                                  tmprowsize++;
                                // ----------- end

                            }
                            
                        fileIn.read( byteInt, 0, 4 );
                        id = CSMDF.byteArrayToInt( byteInt );
                        time.setTime( stime + timeDiffPerID * id );
                      
//                        fileIn.read( byteInt, 0, 4 );
//                        id = byteArrayToInt( byteInt );
//                        System.out.println("CSMF/export id="+id);
//                        time.setTime( stime + timeDiffPerID * id );
                        dateTime = new DateTime( 0, tmprowsize, time, dateFormat );        sheet.addCell( dateTime );

                        for ( int j = 0; j < chSize; j++ ) {
                            fileIn.read( byteDouble, 0, 8 );
                            value = CSMDF.byteArrayToDouble( byteDouble );
                            number = new jxl.write.Number( j + 1, tmprowsize, value, floatFormats[j] );
                            sheet.addCell( number );
                        }

//                        //first record
//                        if(recordRow/onefilelines == (filesize-1)){
//                                label = new Label( 1, 6, DEFAULT_DATE_AND_TIME_FORMAT(time.getTime() ));
//                                sheet.addCell( label );
//                        }
                        //last record
//                        if(((recordRow+1)%onefilelines == 0) || (i == endRecordNo) ){
//                             label = new Label( 3, 6, DEFAULT_DATE_AND_TIME_FORMAT(time.getTime() ));
//                             sheet.addCell( label );
//                        }

                        tmprowsize++;
                    }
                  recordRow++;


                } // cycle of record lines

            }

            fileIn.close();
            workbook.write();
            workbook.close();
            if(tmpFileList.size() >1){

            }
        } catch ( Exception e ) {
            //System.out.println( "CSMDF.exportPHeaderToExcel: " + e.getMessage() );
            e.printStackTrace();
            return DBMessage.CSDB_EXPORT_FAIL;
        }

        return DBMessage.CSDB_OK;
    }
}
