/*
 * ExportDataOptionDialog.java
 *
 * Created on 2007年5月28日, 上午11:36
 */

package com.cs.canalyzer.file.export;

import com.cs.canalyzer.gui.GUIConst;
import com.cs.database.CSMDF;
import com.cs.database.upgrade.DBController;
import com.cs.database.NProtocolHeader;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Timestamp;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  msu
 */
public class ExportDataOptionDialog extends javax.swing.JDialog {
    
    private String pheaderStartTime = null;
    private String pheaderEndTime = null;
    
    /** Creates new form ExportDataOptionDialog */
    public ExportDataOptionDialog(  NProtocolHeader pheader, CSMDF db ) {
        myPHeader = pheader;
        myDB = db;
        
        myInit();
    }

    //add by be on 20100915. deal with the big csd file ------- begin
     public ExportDataOptionDialog(  NProtocolHeader pheader, CSMDF db, boolean isBig ) {
        myPHeader = pheader;
        myDB = db;
        isBigFileToExport = isBig;
//        this.oneFileLines = oneFileLines;
        myInit();
//        jLabel1.setText("You have following options:");
//        jRadioShrink.setText("Export_all_data");
    }
    //------------ end
    
    private void myInit() {
        initComponents();
        
        buttonGroup1.add( jRadioShrink );
        buttonGroup1.add( jRadioSelectPeriod );

        numModelStartHour = new SpinnerNumberModel( 0, 0, 23, 1 );
        jSpinnerStartHour.setModel( numModelStartHour );
        numModelEndHour = new SpinnerNumberModel( 0, 0, 23, 1 );
        jSpinnerEndHour.setModel( numModelEndHour );

        initTimeFields();
        
        jPanelPeriod.setVisible( false );
        pack();
        
        //setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );
        setIconImage( new ImageIcon(getClass().getResource( GUIConst.IMAGE_PATH + GUIConst.LOGO_FILE_NAME)).getImage() );
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation( (dim.width - getWidth()) / 2, (dim.height - getHeight()) / 4 );
    }
    
    private void initTimeFields() {
        try {
            long stime = 0; 
            long etime = 0;
            startTime = Calendar.getInstance();
            endTime = Calendar.getInstance();
            
            stime = myPHeader.StartTime;
            startTime.setTimeInMillis( stime );
            jLabelStart.setText( GUIConst.DEFAULT_DATE_AND_TIME_FORMAT( new Timestamp( stime )));
            jXDatePickerStart.setDate( startTime.getTime() );
            numModelStartHour.setValue( startTime.get( Calendar.HOUR_OF_DAY ) );
            
            long timeMilli = stime + myPHeader.SampleRate * myPHeader.SampleRateFactor * myDB.MAX_EXCEL_LINES_ALLOWED;
            if ( myPHeader.StopTime != NProtocolHeader.DEFAULT_START_AND_END_TIME ) { 
                etime = myPHeader.StopTime;
//                eDate = new Date( etime.getTime() );
                jLabelEnd.setText( GUIConst.DEFAULT_DATE_AND_TIME_FORMAT( new Timestamp( etime )));
//                jXDatePickerEnd.setDate( eDate );
//                if ( etime < timeMilli ) {
                    // the actual endtime is ealier
                    timeMilli = etime;
//                }
            } 
            
            endTime.setTimeInMillis( timeMilli );
            jXDatePickerEnd.setDate( endTime.getTime() );            
            numModelEndHour.setValue( endTime.get( Calendar.HOUR_OF_DAY ) + 1);
           
            try{
                
                if(etime > 0){
                    if((etime/1000) % 3600 == 0){
                       numModelEndHour.setValue(endTime.get( Calendar.HOUR_OF_DAY ));
                    }
                }
                pheaderStartTime = GUIConst.DEFAULT_DATE_FORMAT(new Timestamp( stime )) + " " + numModelStartHour.getNumber().intValue();

                pheaderEndTime = GUIConst.DEFAULT_DATE_FORMAT(new Timestamp( timeMilli )) + " " + numModelEndHour.getNumber().intValue();
            }catch(Exception e){
                pheaderStartTime = null;
                pheaderEndTime = null;
            }
        } catch ( Exception e ) {
            System.out.println( "initTimeFields" + e.getMessage() );
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dateFormats1 = new jxl.write.DateFormats();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioShrink = new javax.swing.JRadioButton();
        jRadioSelectPeriod = new javax.swing.JRadioButton();
        jPanelPeriod = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jXDatePickerEnd = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerStart = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelStart = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerEndHour = new javax.swing.JSpinner();
        jSpinnerStartHour = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts"); // NOI18N
        setTitle(bundle.getString("Export_Option")); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel1.setText(bundle.getString("You_have_following_options")); // NOI18N

        jRadioShrink.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioShrink.setSelected(true);
        jRadioShrink.setText(bundle.getString("Export_all_data")); // NOI18N
        jRadioShrink.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioShrink.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioShrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioShrinkActionPerformed(evt);
            }
        });

        jRadioSelectPeriod.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jRadioSelectPeriod.setText(bundle.getString("Select_a_certain_time_period")); // NOI18N
        jRadioSelectPeriod.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioSelectPeriod.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioSelectPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSelectPeriodActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioSelectPeriod)
                            .add(jRadioShrink)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 458, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel1)
                .add(16, 16, 16)
                .add(jRadioShrink)
                .add(19, 19, 19)
                .add(jRadioSelectPeriod)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanelPeriod.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText(bundle.getString("The_record_file_is_within_this_period")); // NOI18N
        jPanelPeriod.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText(bundle.getString("Which_period_you_want_to_select?")); // NOI18N
        jPanelPeriod.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jXDatePickerEnd.setFormats(GUIConst.DATE_FORMAT_STRING);
        jXDatePickerEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerEndActionPerformed(evt);
            }
        });
        jPanelPeriod.add(jXDatePickerEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jXDatePickerStart.setFormats(GUIConst.DATE_FORMAT_STRING);
        jXDatePickerStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXDatePickerStartActionPerformed(evt);
            }
        });
        jPanelPeriod.add(jXDatePickerStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText(bundle.getString("Hour")); // NOI18N
        jPanelPeriod.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText(bundle.getString("Date")); // NOI18N
        jPanelPeriod.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText(bundle.getString("Hour")); // NOI18N
        jPanelPeriod.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setText(bundle.getString("Date")); // NOI18N
        jPanelPeriod.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText(bundle.getString("To")); // NOI18N
        jPanelPeriod.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabelStart.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabelStart.setForeground(new java.awt.Color(0, 51, 204));
        jLabelStart.setText(bundle.getString("start")); // NOI18N
        jPanelPeriod.add(jLabelStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, -1));

        jLabelEnd.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabelEnd.setForeground(new java.awt.Color(0, 51, 204));
        jLabelEnd.setText(bundle.getString("end")); // NOI18N
        jPanelPeriod.add(jLabelEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 120, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText(bundle.getString("To")); // NOI18N
        jPanelPeriod.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jSpinnerEndHour.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerEndHour.setPreferredSize(new java.awt.Dimension(35, 20));
        jSpinnerEndHour.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerEndHourStateChanged(evt);
            }
        });
        jPanelPeriod.add(jSpinnerEndHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 50, -1));

        jSpinnerStartHour.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSpinnerStartHour.setPreferredSize(new java.awt.Dimension(35, 20));
        jSpinnerStartHour.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerStartHourStateChanged(evt);
            }
        });
        jPanelPeriod.add(jSpinnerStartHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, -1));

        getContentPane().add(jPanelPeriod, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 30));

        jButtonOK.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButtonOK.setText(bundle.getString("OK")); // NOI18N
        jButtonOK.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOK);

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jButton2.setText(bundle.getString("Cancel")); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(95, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXDatePickerEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerEndActionPerformed
//        Calendar c = Calendar.getInstance();
//        c.setTime( jXDatePickerEnd.getDate() ); 
//        long timeMilli = startTime.getTimeInMillis() +  (long)myPHeader.SampleRate * myPHeader.SampleRateFactor * 
//                            CSMDF.MAX_EXCEL_LINES_ALLOWED;
        //if ( c.getTimeInMillis() > timeMilli )
        verifySelectedEndTime();
        
    }//GEN-LAST:event_jXDatePickerEndActionPerformed

    private boolean verifySelectedEndTime() {
        // end time
        Calendar c = Calendar.getInstance();
        c.setTime( jXDatePickerEnd.getDate() ); 
        c.set( Calendar.HOUR_OF_DAY, numModelEndHour.getNumber().intValue() );
        c.set( Calendar.MINUTE, 0 );
        c.set( Calendar.SECOND, 0 );
        c.set( Calendar.MILLISECOND, 0 ); 
       
        if(c.getTimeInMillis() <= startTime.getTimeInMillis()){
            JOptionPane.showMessageDialog(this,java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("End_time_must_be_after_start_time"));
            return false;
        }
        if((c.getTimeInMillis()-myPHeader.StopTime) >= myDB.ONE_HOUR_MILLS){
            if(pheaderStartTime != null && pheaderEndTime != null){
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("The_valid_record_time_is_from")
                        + " '"+ pheaderStartTime + "' " + java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("starttime_to_endtime") + " '" + pheaderEndTime + "', " + java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("endtime_setting_over_range"));
            }
            return false;
        }else if( (c.getTimeInMillis()-myPHeader.StopTime) > 0 &&
                (c.getTimeInMillis()-myPHeader.StopTime) < myDB.ONE_HOUR_MILLS){
            c.setTimeInMillis( myPHeader.StopTime );
        }
        
        
//        if ( c.getTimeInMillis() > myPHeader.StopTime ) {
//            c.setTimeInMillis( myPHeader.StopTime );
//        }
//        if ( c.getTimeInMillis() <= startTime.getTimeInMillis() ) {
//            c.setTimeInMillis( startTime.getTimeInMillis() + (long)myPHeader.SampleRate * myPHeader.SampleRateFactor );
//        }
        
        //long timeMilli = startTime.getTimeInMillis() + myPHeader.srate * 1000 * DBController.MAX_EXCEL_LINES_ALLOWED;
        //if ( c.getTimeInMillis() > timeMilli ) {
//        if(isBigFileToExport){//add by be on 20100915.
//             endTime.setTimeInMillis( c.getTimeInMillis() );
//             System.out.println("oneFileLines="+oneFileLines);
//             if ( (getEndID()-getStartID()) > oneFileLines ) {
//
//                return false;
//            }
//        }else{
//            if ( myDB.recordsPerChannelWithinCertainPeriod( myPHeader.Pref, startTime.getTimeInMillis(), c.getTimeInMillis() )
//                    > DBController.MAX_EXCEL_LINES_ALLOWED ) {
//                return false;
//            }
//        }
        
        endTime.setTimeInMillis( c.getTimeInMillis() );
        
        return true;
    }

    private boolean verifySelectedStartTime() {
        // start time
        Calendar c = Calendar.getInstance();
        c.setTime( jXDatePickerStart.getDate() ); 
//System.out.println( "selected date: "  + c.toString() );
        c.set( Calendar.HOUR_OF_DAY, numModelStartHour.getNumber().intValue() );
        c.set( Calendar.MINUTE, 0 );
        c.set( Calendar.SECOND, 0 );
        c.set( Calendar.MILLISECOND, 0 ); 
        
        if(c.getTimeInMillis() >= endTime.getTimeInMillis()){
            JOptionPane.showMessageDialog(this,java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("Start_time_must_be_before_end_time"));
            return false;
        }
        
        if ( myPHeader.StartTime - c.getTimeInMillis() >= myDB.ONE_HOUR_MILLS ||
                c.getTimeInMillis() > myPHeader.StopTime )  {
            
            if(pheaderStartTime != null && pheaderEndTime != null){
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("The_valid_record_time_is_from")
                       + " '" + pheaderStartTime + "' " + java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("starttime_to_endtime")+" '" + pheaderEndTime + "', " + java.util.ResourceBundle.getBundle("com/cs/canalyzer/CAATexts").getString("startime_setting_overrange"));
            }
            return false;
        }else if( (myPHeader.StartTime - c.getTimeInMillis()) > 0 
                && (myPHeader.StartTime - c.getTimeInMillis()) < myDB.ONE_HOUR_MILLS){
            c.setTimeInMillis( myPHeader.StartTime );
            jXDatePickerStart.setDate( c.getTime() );
            numModelStartHour.setValue( c.get( Calendar.HOUR_OF_DAY ) );
//            return false;
        }
        
        startTime.setTimeInMillis( c.getTimeInMillis() );
        
        return true;
    }
    
    private void jXDatePickerStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXDatePickerStartActionPerformed
        if ( !verifySelectedStartTime() ) {
            //jXDatePickerStart.setDate( startTime.getTime() );
        }
    }//GEN-LAST:event_jXDatePickerStartActionPerformed

    private void jSpinnerStartHourStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerStartHourStateChanged
        if ( !verifySelectedStartTime() ) {}
    }//GEN-LAST:event_jSpinnerStartHourStateChanged

    private void jSpinnerEndHourStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerEndHourStateChanged
        verifySelectedEndTime();        
    }//GEN-LAST:event_jSpinnerEndHourStateChanged

    private void jRadioShrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioShrinkActionPerformed
        selection = SELECTION_SHRINK;
        jPanelPeriod.setVisible( false );
        pack();
    }//GEN-LAST:event_jRadioShrinkActionPerformed

    private void jRadioSelectPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSelectPeriodActionPerformed
        selection = SELECTION_SELECT_TIME_PERIOD;
        jPanelPeriod.setVisible( true );
        pack();
    }//GEN-LAST:event_jRadioSelectPeriodActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        if ( selection != SELECTION_SHRINK ) {
            if ( !verifySelectedStartTime() ) {
                return;
            }
            if ( !verifySelectedEndTime() ) {
//                if(isBigFileToExport){
//                    JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/Main/eng").getString("selected_exceed_limit_please_re_select") );
//                }else{
//                    JOptionPane.showMessageDialog( this, java.util.ResourceBundle.getBundle("com/cs/Main/eng").getString("selected_exceed_limit_please_re_select") );
//                }
                return;
            }
        }
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        selection = SELECTION_CANCEL;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    public int getStartID() {
        int id;
        long timeMilli = startTime.getTimeInMillis();
        long stimeMilli = myPHeader.StartTime;
        if ( timeMilli <= stimeMilli ) {
            id = 0;
        } else {
            id = (int) (( timeMilli - stimeMilli ) / ( myPHeader.SampleRate * myPHeader.SampleRateFactor ) + 1 );
        }
        System.out.println("ExportDataOptionDialog/getStartID="+id);
        return id;
    }
    
    public int getEndID() {
        int id;
        long timeMilli = endTime.getTimeInMillis();
        long stimeMilli = myPHeader.StartTime;

        id = (int) (( timeMilli - stimeMilli ) / ( myPHeader.SampleRate * myPHeader.SampleRateFactor ));
        
        if ( id < 0 )
            id = 0;

        System.out.println("ExportDataOptionDialog/getEndID="+id);
        return id;
    }
    
    public int getSelection() {
        return selection;
    }
    
    
    private final int WIDTH = 400;
    private final int HEIGHT = 350;
    
    public final static int SELECTION_SHRINK = 0;
    public final static int SELECTION_SELECT_TIME_PERIOD = 1;
    public final static int SELECTION_CANCEL = 2;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private jxl.write.DateFormats dateFormats1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPeriod;
    private javax.swing.JRadioButton jRadioSelectPeriod;
    private javax.swing.JRadioButton jRadioShrink;
    private javax.swing.JSpinner jSpinnerEndHour;
    private javax.swing.JSpinner jSpinnerStartHour;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerEnd;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerStart;
    // End of variables declaration//GEN-END:variables
    
    //private javax.swing.ButtonGroup buttonGroup1;
    private int selection = SELECTION_SHRINK;
    
    private NProtocolHeader myPHeader;
    private CSMDF myDB;
    
    private SpinnerNumberModel numModelStartHour;
    private SpinnerNumberModel numModelEndHour;
    
    private Calendar startTime, endTime;

    //add by be on 20100915 ---------- begin
    private boolean isBigFileToExport = false;
//    private long oneFileLines = 0;
    //------------------------ end
    
}
